### PR TITLE
[RemoteSpecification] Fail gracefully when deps is an array of array of string

### LINKED ISSUE #5797: bundler error
Running bundler
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/var/lib/jenkins/.rvm/gems/ruby-2.3.3/bin/bundle install --quiet`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
NoMethodError: undefined method `type' for ["ruby-ajp", ">= 0.2.0"]:Array
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:121:in `block (2 levels) in dependency_names'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:120:in `each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:120:in `block in dependency_names'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:105:in `each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:105:in `block in each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:104:in `each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:104:in `each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:119:in `dependency_names'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:377:in `block (3 levels) in remote_specs'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:375:in `each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:375:in `block (2 levels) in remote_specs'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:373:in `loop'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:373:in `block in remote_specs'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:10:in `build'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:345:in `remote_specs'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:82:in `specs'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:263:in `block (2 levels) in index'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:261:in `each'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:261:in `block in index'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/index.rb:10:in `build'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:258:in `index'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:252:in `resolve'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/definition.rb:164:in `resolve_remotely!'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/installer.rb:226:in `resolve_if_need'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/installer.rb:78:in `run'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli/install.rb:70:in `run'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:181:in `block in install'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/settings.rb:99:in `temporary'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:180:in `install'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `load'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `<main>'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
  /var/lib/jenkins/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.10
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
GEM_HOME  /var/lib/jenkins/.rvm/gems/ruby-2.3.3
GEM_PATH  /var/lib/jenkins/.rvm/gems/ruby-2.3.3:/var/lib/jenkins/.rvm/gems/ruby-2.3.3@global
RVM       1.29.1 (latest)
Git       2.11.0
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1 14 Mar 2012
```

## Bundler settings

```
bin
  Set for the current user (/var/lib/jenkins/.bundle/config): "bin"
```

--- TEMPLATE END ----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by segiddins**
Instead of containing Gem::Dependency objects

### What was the end-user problem that led to this PR?

The problem was some gems have invalid gemspecs served by RubyGems.org. See https://github.com/bundler/bundler/issues/5797.

### Was was your diagnosis of the problem?

My diagnosis was (very old) some gemspecs can have `s.dependencies = [["name", "req"]]` instead of `s.dependencies = [Gem::Dependency.new("name", "req")]`.

### What is your fix for the problem, implemented in this PR?

My fix coerces the invalid dependencies to an array of dependency objects so we can fail more gracefully during installation, without spitting out the error template.

Closes #5797.

### Why did you choose this fix out of the possible options?

I chose this fix because it allows resolution to finish, and falls back upon existing error messages.

### CODE REVIEW

**Comment by segiddins** [comment]
Fails only on RG 1.7.2, because of course it's invalid. Can restrict the spec to only recent RG versions if this looks reasonable

**Comment by segiddins** [comment]
Restricted to most recent RG versions & rebased

File: lib/bundler/remote_specification.rb [hunk 1]
```diff
@@ -73,7 +73,15 @@ def to_s
     end
 
     def dependencies
-      @dependencies || method_missing(:dependencies)
+      @dependencies ||= begin
+        deps = method_missing(:dependencies)
+        unless deps.all? {|d| d.is_a?(Gem::Dependency) }
+          # allow us to handle when the specs dependencies are an array of array of string
+          # see https://github.com/bundler/bundler/issues/5797
+          deps.map! {|d| Gem::Dependency.new(*d) }
```
Comment (jules2689) [inline lib/bundler/remote_specification.rb]: This logic states that you map all deps to a G::D, but what happens if (for some unknown reason), we have `[G::D, ['',''], G::D]`. In this example, you'd init a G::D with a G::D - which might be ok (I'm not sure).

Since `deps.all` already iterates through everything, what if we collapsed to this:
```ruby
deps = deps.map { |d| d.is_a?(Gem::Depencency) ? d :  Gem::Dependency.new(*d) }
```

Comment (segiddins) [inline lib/bundler/remote_specification.rb]: `Gem::Dependency` implements `to_a` so its kosher

Comment (segiddins) [inline lib/bundler/remote_specification.rb]: but collapsing to a single map seems reasonable as well

Comment (segiddins) [inline lib/bundler/remote_specification.rb]: changed

**Comment by indirect** [comment]
This seems like a reasonable way to work around the upstream issue—how do you feel about solving the issue upstream by yanking these invalid gems? (Or replacing their gemspecs with valid gemspecs).

**Comment by segiddins** [comment]
@indirect seems reasonable, but this should be a better way to find out about which gems have the problem than barfing up the error template

**Comment by indirect** [comment]
@segiddins okay, that's fair. @bundlerbot r+
