### PR TITLE
[Definition] Allow unlocking when removing the ruby version requirement

### LINKED ISSUE #4595: `bundle install` does not always sync locked RUBY VERSION with Gemfile specification
When you remove the ruby version specified from the `Gemfile`, `bundle install` seems to only remove the locked `RUBY VERSION` from the `Gemfile.lock` if you have also removed or updated some other gem specification in your `Gemfile`.

`bundle env` output:
```bash
Environment

    Bundler   1.12.4
    Rubygems  2.5.1
    Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    GEM_HOME  /Users/pivotal/.rvm/gems/ruby-2.3.0
    GEM_PATH  /Users/pivotal/.rvm/gems/ruby-2.3.0:/Users/pivotal/.rvm/gems/ruby-2.3.0@global
    RVM       1.27.0 (master)
    Git       2.7.3
    rubygems-bundler (1.4.4)

Bundler settings

    gem.coc
      Set for the current user (/Users/pivotal/.bundle/config): "false"
    gem.mit
      Set for the current user (/Users/pivotal/.bundle/config): "true"
    gem.test
      Set for the current user (/Users/pivotal/.bundle/config): "rspec"
    orig_path
      Set via BUNDLE_ORIG_PATH: "/Users/pivotal/.rvm/gems/ruby-2.3.0/bin:/Users/pivotal/.rvm/gems/ruby-2.3.0@global/bin:/Users/pivotal/.rvm/rubies/ruby-2.3.0/bin:/Users/pivotal/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet/bin:/Users/pivotal/workspace/go/bin:/Users/pivotal/bin:/Applications/Emacs.app/Contents/MacOS/bin:/Users/pivotal/miniconda3/bin"
    orig_gem_path
      Set via BUNDLE_ORIG_GEM_PATH: "/Users/pivotal/.rvm/gems/ruby-2.3.0:/Users/pivotal/.rvm/gems/ruby-2.3.0@global"

Gemfile

    source 'https://rubygems.org'
    ruby "2.3.0"

    gem 'activesupport', '4.2.5'
    gem 'thor'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        activesupport (4.2.5)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        i18n (0.7.0)
        json (1.8.3)
        minitest (5.9.0)
        thor (0.19.1)
        thread_safe (0.3.5)
        tzinfo (1.2.2)
          thread_safe (~> 0.1)

    PLATFORMS
      ruby

    DEPENDENCIES
      activesupport (= 4.2.5)
      thor

    RUBY VERSION
       ruby 2.3.0p0

    BUNDLED WITH
       1.12.4
```

- Remove `ruby "2.3.0"` line from `Gemfile`:
```ruby
source 'https://rubygems.org'
gem 'activesupport', '4.2.5'
gem 'thor'
```
- Run `bundle install`
- The RUBY VERSION has not been removed in the resulting `Gemfile.lock`:
```ruby
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.9.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (= 4.2.5)
  thor

RUBY VERSION
   ruby 2.3.0p0

BUNDLED WITH
   1.12.4
```

If instead of just removing the `ruby "2.3.0"` line from `Gemfile`, you also remove the `gem 'thor'` line:
```ruby
source 'https://rubygems.org'

gem 'activesupport', '4.2.5'
```
and run `bundle install`, the resulting `Gemfile.lock` has the `RUBY VERSION` removed:

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.9.0)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (= 4.2.5)

BUNDLED WITH
   1.12.4
```

Reproduction steps by @thewoolleyman

### LINKED ISSUE #4627: Bundler allows Incompatible Ruby versions in Gemfile and Gemfile.lock
If you have `ruby "2.3.0"` in your Gemfile and `bundle install` then you'll get this in your Gemfile.lock:

```
RUBY VERSION
   ruby 2.3.0p0
```

Now if you want to update your project to the latest and you set `ruby "2.3.1"` in your Gemfile, and you run `bundle install`, nothing will change.

When you run `bundle platform --ruby` even though you have `ruby "2.3.1"`  specified, you'll still get:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
$ bundle install
  # ... 
$ cat Gemfile | grep ruby
source 'https://rubygems.org'
ruby '2.3.1'
$ bundle _1.12.5_ platform --ruby
ruby 2.3.0p0
```

I'm thinking we should detect when the stored Ruby version does not satisfy the version specification and update the Gemfile.lock.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4595. Closes #4627.

\c @RochesterinNYC

### CODE REVIEW

**Comment by segiddins** [comment]
Not sure if those failures need to be fixed or are actually also showing that we've 'fixed' things

**Comment by RochesterinNYC** [comment]
I think that those spec failures around `Resolving dependencies...` now being outputted for those scenarios are indeed caused by this new behavior so those specs should probably be tweaked.

**Comment by segiddins** [comment]
@homu delegate=RochesterinNYC

**Comment by schneems** [comment]
Here's where I added your code:

```
$ sed -n '85,92p;' /Users/richardschneeman/.gem/ruby/2.3.1/gems/bundler-1.12.5/lib/bundler/definition.rb

      @unlock[:gems] ||= []
      @unlock[:sources] ||= []
      @unlocking ||= @unlock[:ruby] || (!@locked_ruby_version ^ !@ruby_version)

      current_platform = Bundler.rubygems.platforms.map {|p| generic(p) }.compact.last
      @new_platform = !@platforms.include?(current_platform)
      @platforms |= [current_platform]
```

Then in the same project I run bundle install:

```
$ bundle _1.12.5_ install
Resolving dependencies...
# ...
Bundle complete! 57 Gemfile dependencies, 138 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

I don't get an updated version:

```
$ bundle _1.12.5_ platform --ruby
ruby 2.3.0p0
```

If I try to `update` a gem

```
$ bundle _1.12.5_ update bourbon
# ...
Installing bourbon 4.2.7 (was 4.2.5)
Using neat 1.7.2
Bundle updated!
```

Then I still get the same output

```
$ bundle _1.12.5_ platform --ruby
ruby 2.3.0p0
```

**Comment by indirect** [comment]
@segiddins is this ready to go, or did the experimental results from Heroku mean it needs further refinement?

**Comment by segiddins** [comment]
I have a big change I'll push up later

File: lib/bundler/ruby_version.rb [hunk 1]
```diff
@@ -38,6 +38,24 @@ def to_s(versions = self.versions)
       output
     end
 
+    # @private
+    PATTERN = %r{
+      ruby\s
```
Comment (indirect) [inline lib/bundler/ruby_version.rb]: pretty sure the "ruby " part of this is supposed to be optional? I see a lot of .ruby-version files that are only, say, "2.2.3".

Comment (segiddins) [inline lib/bundler/ruby_version.rb]: The `from_string` accepts a string generated by `RubyVersion#to_s

**Comment by RochesterinNYC** [comment]
I'll help manually verify this tomorrow.

**Comment by RochesterinNYC** [comment]
Manually verified that this fixes the explicit problem in #4595.

**Comment by segiddins** [comment]
@RochesterinNYC should be fixed now, can you verify you're OK with the behavior changes in the specs?

File: lib/bundler/ruby_version.rb [hunk 2]
```diff
@@ -38,6 +38,22 @@ def to_s(versions = self.versions)
...
+      (?:p(\d+))? # optional patchlevel
+      (?:\s\((\S+)\s(.+)\))? # optional engine info
+    /xo
+
+    # Returns a RubyVersion from the given string.
+    # @param [String] the version string to match.
+    # @return [RubyVersion,Nil] The version if the string is a valid RubyVersion
+    #         description, and nil otherwise.
+    def self.from_string(string)
+      new($1, $2, $3, $4) if string =~ PATTERN
```
Comment (RochesterinNYC) [inline lib/bundler/ruby_version.rb]: Nice. I like this method/implementation.

File: lib/bundler/ruby_version.rb [hunk 3]
```diff
@@ -64,7 +80,7 @@ def host
     #   2. ruby_version
     #   3. engine_version
     def diff(other)
-      raise ArgumentError, "Can only diff with a RubyVersion" unless other.is_a?(RubyVersion)
+      raise ArgumentError, "Can only diff with a RubyVersion, not a #{other.class}" unless other.is_a?(RubyVersion)
```
Comment (RochesterinNYC) [inline lib/bundler/ruby_version.rb]: Is there test coverage for this?

File: spec/bundler/ruby_version_spec.rb [hunk 4]
```diff
@@ -56,6 +56,40 @@
         end
       end
     end
+
+    describe ".from_string" do
+      shared_examples_for "returning" do
+        it "returns the original RubyVersion" do
```
Comment (RochesterinNYC) [inline spec/bundler/ruby_version_spec.rb]: this'll read like:
```
.from_string
  returning
    returns the original RubyVersion
```
wouldn't something like this be more accurate/readable?
```
.from_string
  on a string representing a ruby version
    returns a RubyVersion
```

File: spec/support/helpers.rb [hunk 5]
```diff
@@ -347,6 +347,15 @@ def simulate_platform(platform)
       ENV["BUNDLER_SPEC_PLATFORM"] = old if block_given?
     end
 
+    def simulate_ruby_version(version)
+      return if version == RUBY_VERSION
+      old = ENV["BUNDLER_SPEC_RUBY_VERSION"]
```
Comment (RochesterinNYC) [inline spec/support/helpers.rb]: Couldn't you move the `spec/support/hax.rb` logic around manipulating `Object`'s constants into the `simulate_ruby_version` method? So the fairly interesting/tricky logic's not distributed across two classes.

File: spec/install/gemfile/ruby_spec.rb [hunk 6]
```diff
@@ -22,4 +26,64 @@
...
+  it "allows changing the ruby version requirement to something compatible" do
+    install_gemfile <<-G
+      source "file://#{gem_repo1}"
+      ruby ">= 1.0.0"
+      gem "rack"
+    G
+
+    expect(locked_ruby_version).to eq(Bundler::RubyVersion.system)
+
+    simulate_ruby_version "5100"
```
Comment (RochesterinNYC) [inline spec/install/gemfile/ruby_spec.rb]: These invocations don't restore the RUBY_VERSION and ENV["BUNDLER_SPEC_RUBY_VERSION"] afterwards right? Should we be invoking the following calls/assertions within blocks passed to `simulate_ruby_version`?

File: spec/support/helpers.rb (hunk 5 above)
Comment (RochesterinNYC) [inline spec/support/helpers.rb]: Scratch that, seems like `remove_const` is private so that wouldn't work. Never mind!

File: lib/bundler/ruby_version.rb (hunk 3 above)
Comment (segiddins) [inline lib/bundler/ruby_version.rb]: we typically don't test the message from `ArgumentError`s and the like, since they're mor a debugging tool than anything else

File: spec/bundler/ruby_version_spec.rb (hunk 4 above)
Comment (segiddins) [inline spec/bundler/ruby_version_spec.rb]: no it won't since the examples are included, instead of being nested in another context

File: spec/support/helpers.rb (hunk 5 above)
Comment (segiddins) [inline spec/support/helpers.rb]: `hax.rb` is loaded into the bundler subprocess

File: spec/install/gemfile/ruby_spec.rb (hunk 6 above)
Comment (segiddins) [inline spec/install/gemfile/ruby_spec.rb]: the entire ENV gets restored for each example

**Comment by indirect** [comment]
@homu r+

**Comment by schneems** [comment]
Thanks for your work here, is there an ETA on Bundler 1.12.6?

**Comment by segiddins** [comment]
@schneems nah, I should be starting the 1.13 series early this week though

**Comment by schneems** [comment]
Any major changes to be aware of with the 1.13 series? I'm blocked on getting Heroku on ruby version specifiers until this patch is released in the wild.

**Comment by indirect** [comment]
@schneems the primary changes are improvements to the efficiency of the resolver, reducing memory used, objects allocated, and time taken. There's also a prototype of the plugin system, disabled behind a feature flag.

After talking it over, we'd like to release this fix in a (future) 1.12 bugfix release, but it is big enough that we want to get some testing for it in a prerelease first. I'd like to backport this fix to the 1.12 series once we're more confident that it's solid.

**Comment by schneems** [comment]
Great! Let me know and i'll help spread the word to get some people testing the pre-release. Thanks for all the work.

**Comment by schneems** [comment]
Any idea when or if we might get a 1.12 bugfix release?

**Comment by segiddins** [comment]
Not on my timeline personally, but 1.13 final should be out imminently, we've already released 1.13.0.rc.2

**Comment by schneems** [comment]
Historically we've had to wait a while after the first stable release for all the bugs to be worked out. I've been waiting on supporting ruby version specifiers for about 2 months now. The only thing 1.12 is missing for us that I know of is this one fix. I was hoping to be able to release 1.12 right away and then adopt 1.13 as soon as it's bug free.

**Comment by segiddins** [comment]
You're welcome to use the 1.13 RCs in the meantime

**Comment by schneems** [comment]
Historically we've had to wait a while after the first stable release for all the bugs to be worked out.

**Comment by segiddins** [comment]
Any bugs in particular in this build?

**Comment by schneems** [comment]
Not that I know of, if you're saying the RC is really really stable then we can try putting the RC up on master. I just installed it locally and hit this https://github.com/bundler/bundler/issues/4953

**Comment by schneems** [comment]
Looks like there were some bugs between the RC and now. I've got 1.13.1 built and staged in S3, going to wait until i'm not at a conference to push it to master. Probably looking at early next week.

**Comment by segiddins** [comment]
Please file issues for any new bugs, as this is a merged PR
