### PR TITLE
[Fix #5358] Handle files conflicts when using `bundle gem`

### LINKED ISSUE #5358: Gracefully handle error in `bundle gem`
- **What did you do?**

```
$ mkdir issue
$ touch hello
$ bundle gem hello
```

- **What did you expect to happen?**

Gracefully handle the fact that a file named `hello` already exist in the directory. Maybe ask user input about how to proceed. E.g. overwrite / abort.

- **What happened instead?**

Bundler showed the unexpected error template. 
I.e.
```
*Unfortunately, an unexpected error occurred, and Bundler cannot continue.* 
```

I would be happy to pick the issue if you wish. It does not seem a complex fix. What do you think?

## Backtrace

```
Errno::EEXIST: File exists @ dir_s_mkdir - /private/tmp/bundler_issue/hello
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:228:in `mkdir'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:228:in `fu_mkdir'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:206:in `block (2 levels) in mkdir_p'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:204:in `reverse_each'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:204:in `block in mkdir_p'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:190:in `each'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:190:in `mkdir_p'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/actions/create_file.rb:61:in `block in invoke!'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/actions/create_file.rb:60:in `invoke!'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/actions.rb:94:in `action'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/actions/create_file.rb:25:in `create_file'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/actions/file_manipulation.rb:115:in `template'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/cli/gem.rb:125:in `block in run'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/cli/gem.rb:124:in `each'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/cli/gem.rb:124:in `run'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/cli.rb:433:in `run'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/cli.rb:20:in `dispatch'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/cli.rb:11:in `start'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/exe/bundle:32:in `block in <top (required)>'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.2/exe/bundle:24:in `<top (required)>'
  /Users/anodari/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
  /Users/anodari/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.2
Rubygems  2.6.8
Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
Git       2.10.0
Platform  x86_64-darwin-15
```

### PR DESCRIPTION
**Pull request by nodo**
`bundle gem` command fails with an exception when creating a gem having
the same name of a file in the specified path.

For instance:
> touch hello
> bundle gem hello

This bug is due to Thor gem. At the moment, Thor does not handle
conflicts between files and directories. This commit mitigates the
problem by rescuing the exception from Thor and gracefully exit with an
error message.

Fixes https://github.com/bundler/bundler/issues/5358

### CODE REVIEW

File: lib/bundler/cli/gem.rb [hunk 1]
```diff
@@ -139,6 +139,10 @@ def run
 
       # Open gemspec in editor
       open_editor(options["edit"], target.join("#{name}.gemspec")) if options[:edit]
+    rescue SystemCallError => e
```
Comment (segiddins) [inline lib/bundler/cli/gem.rb]: Please use `SharedHelpers.filesystem_access` instead of this

Comment (nodo) [inline lib/bundler/cli/gem.rb]: @segiddins the error is thrown by `thor.template`. Should I monkey-patch it? Or how would you use `SharedHelpers.filesystem_access`?

Comment (nodo) [inline lib/bundler/cli/gem.rb]: Nevermind the comment above 👍  Will do it, thanks!

Comment (nodo) [inline lib/bundler/cli/gem.rb]: @segiddins I have just noticed that here https://github.com/bundler/bundler/blob/master/lib/bundler/shared_helpers.rb#L120 when `Errno::EEXIST` happen a generic `RuntimeError` is thrown. Are you OK if I create a custom exception for that?

Comment (segiddins) [inline lib/bundler/cli/gem.rb]: ah in that case, please use both `filesystem_access` and separately rescue `EEXIST` and raise a `GenericSystemCallError` for it?

**Comment by nodo** [comment]
@segiddins I have updated the PR. What do you think?

**Comment by segiddins** [comment]
Thanks!
@bundlerbot r+
