### PR TITLE
Avoid deadlocking when installing with a lockfile missing dependencies

### LINKED ISSUE #5378: Deadlock detected in ancient Rails app.
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/home/darrint/.rvm/gems/ruby-1.9.3-p551/bin/bundle install`

- **What did you expect to happen?**

  I expected Bundler to install dependencies for this ancient rails app.

- **What happened instead?**

  Deadlock detected error.

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried messing with the jobs setting and removing the bundle and reinstalling.

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/ISSUES.md?**

  Yep
  ...

## Backtrace

```                                                                                                            [7/102]
fatal: deadlock detected
  /home/darrint/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/thread.rb:189:in `sleep'
  /home/darrint/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/thread.rb:189:in `block in pop'
  <internal:prelude>:10:in `synchronize'
  /home/darrint/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/thread.rb:184:in `pop'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `deq'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:131:in `proc
ess_specs'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:102:in `call
'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer.rb:199:in `install_in_parallel'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer.rb:166:in `install'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer.rb:80:in `run'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/installer.rb:24:in `install'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/cli/install.rb:70:in `run'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/cli.rb:181:in `block in install'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/settings.rb:99:in `temporary'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/cli.rb:180:in `install'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `i
nvoke_command'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_err
ors'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/bin/bundle:22:in `load'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/bin/bundle:22:in `<main>'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
  /home/darrint/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

## Environment

```
Bundler   1.14.3
Rubygems  2.6.10
Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
GEM_HOME  /home/darrint/herring/bundle/ruby/1.9.1
GEM_PATH
RVM       1.28.0 (latest)
Git       2.11.0
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.2k  26 Jan 2017
```

## Bundler settings

```
jobs
  Set for the current user (/home/darrint/.bundle/config): "1"
path
  Set for your local app (/home/darrint/herring/upload/.bundle/config): "../bundle"
#bundle_disable_shared_gems
  You have not configured a value for `#bundle_disable_shared_gems`
disable_shared_gems
  Set for your local app (/home/darrint/herring/upload/.bundle/config): true
```

### LINKED ISSUE #5480: fatal: No live threads left. Deadlock?
Hi,

 I am trying to install tarantula on a ubuntu machine, i'm unable to get past this issue. It doesn't help i never dealt with ruby and gems.
Any help is greatly appreciated.

--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `sudo bash install.sh`

- **What did you expect to happen?**

  I expected the script to run completely  with installing packages and Tarantula files

- **What happened instead?**

the below error.

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

Yes, but could not get past this issue.

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

Yes

## Backtrace

```
fatal: No live threads left. Deadlock?
  /usr/local/lib/ruby/2.0.0/thread.rb:72:in `sleep'
  /usr/local/lib/ruby/2.0.0/thread.rb:72:in `block (2 levels) in wait'
  /usr/local/lib/ruby/2.0.0/thread.rb:68:in `handle_interrupt'
  /usr/local/lib/ruby/2.0.0/thread.rb:68:in `block in wait'
  /usr/local/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
  /usr/local/lib/ruby/2.0.0/thread.rb:66:in `wait'
  /usr/local/lib/ruby/2.0.0/thread.rb:196:in `block (2 levels) in pop'
  /usr/local/lib/ruby/2.0.0/thread.rb:188:in `synchronize'
  /usr/local/lib/ruby/2.0.0/thread.rb:188:in `block in pop'
  /usr/local/lib/ruby/2.0.0/thread.rb:187:in `handle_interrupt'
  /usr/local/lib/ruby/2.0.0/thread.rb:187:in `pop'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/worker.rb:43:in `deq'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer.rb:199:in `install_in_parallel'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer.rb:166:in `install'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer.rb:80:in `run'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/installer.rb:24:in `install'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/cli/install.rb:70:in `run'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/cli.rb:181:in `block in install'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/settings.rb:99:in `temporary'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/cli.rb:180:in `install'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler   1.14.5
Rubygems  2.0.14
Ruby      2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
GEM_HOME  /opt/tarantula/rails/vendor/bundle/ruby/2.0.0
GEM_PATH
Git       1.7.9.5
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1 14 Mar 2012
```

## Bundler settings

```
specific_platform
  Set for the current user (/home/ubuntu/.bundle/config): "true"
frozen
  Set for your local app (/opt/tarantula/rails/.bundle/config): "1"
path
  Set for your local app (/opt/tarantula/rails/.bundle/config): "vendor/bundle"
disable_shared_gems
  Set for your local app (/opt/tarantula/rails/.bundle/config): true
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

### LINKED ISSUE #5519: Addressable not updating
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/usr/local/bin/bundle update addressable`

- **What did you expect to happen?**

  I expected Bundler to update addressable so I could use jekyll for Bootstrap

- **What happened instead?**

  Instead, what happened was that I got an error and "Your lockfile was created by an old Bundler that left some things out.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
The missing gems are:
* addressable depended upon by jekyll-sitemap"

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried using exec but that led to more issues. 

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

  Yess

## Backtrace

```
fatal: No live threads left. Deadlock?
27 threads, 27 sleeps current:0x007feb4b406ac0 main thread:0x007feb4b406ac0
* #<Thread:0x007feb4b87ca60 sleep_forever>
   rb_thread_t:0x007feb4b406ac0 native:0x007fff7438c000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `deq'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:102:in `call'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:77:in `call'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:199:in `install_in_parallel'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:166:in `install'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:80:in `run'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/update.rb:55:in `run'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:221:in `update'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
   /usr/local/bin/bundle:22:in `load'
   /usr/local/bin/bundle:22:in `<main>'
* #<Thread:0x007feb4fccccb0@Compact Index (rubygems.org) Worker #0@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ed8ff50 native:0x00700000108000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fccc580@Compact Index (rubygems.org) Worker #1@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4b5b4e70 native:0x0070000020b000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc7f80@Compact Index (rubygems.org) Worker #2@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9f8ae0 native:0x0070000030e000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc79e0@Compact Index (rubygems.org) Worker #3@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef17240 native:0x00700000411000 int:1
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc7440@Compact Index (rubygems.org) Worker #4@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9a0230 native:0x00700000514000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc6ea0@Compact Index (rubygems.org) Worker #5@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9b07a0 native:0x00700000617000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc6900@Compact Index (rubygems.org) Worker #6@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef2e480 native:0x0070000071a000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc6388@Compact Index (rubygems.org) Worker #7@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9e62e0 native:0x0070000081d000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc5de8@Compact Index (rubygems.org) Worker #8@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e985030 native:0x00700000920000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc5848@Compact Index (rubygems.org) Worker #9@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e985eb0 native:0x00700000a23000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc52a8@Compact Index (rubygems.org) Worker #10@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef39180 native:0x00700000b26000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc4d08@Compact Index (rubygems.org) Worker #11@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef48d50 native:0x00700000c29000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc4768@Compact Index (rubygems.org) Worker #12@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e949c60 native:0x00700000d2c000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcc41c8@Compact Index (rubygems.org) Worker #13@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e997750 native:0x00700000e2f000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbfbf0@Compact Index (rubygems.org) Worker #14@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e94ab00 native:0x00700000f32000 int:1
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbf650@Compact Index (rubygems.org) Worker #15@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9da250 native:0x00700001035000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbf0b0@Compact Index (rubygems.org) Worker #16@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef08d00 native:0x00700001138000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbeb10@Compact Index (rubygems.org) Worker #17@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef1d530 native:0x0070000123b000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbe570@Compact Index (rubygems.org) Worker #18@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef35ae0 native:0x0070000133e000 int:1
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbdfd0@Compact Index (rubygems.org) Worker #19@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef52960 native:0x00700001441000 int:1
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbda30@Compact Index (rubygems.org) Worker #20@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e988630 native:0x00700001544000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbd558@Compact Index (rubygems.org) Worker #21@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e991f90 native:0x00700001647000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbd080@Compact Index (rubygems.org) Worker #22@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4ef18480 native:0x0070000174a000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbcae0@Compact Index (rubygems.org) Worker #23@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9f0120 native:0x0070000184d000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4fcbc540@Compact Index (rubygems.org) Worker #24@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb4e9e0ea0 native:0x00700001950000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'
* #<Thread:0x007feb4bbb9e58@Parallel Installer Worker #0@/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007feb526e8220 native:0x00700001a53000 int:0
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `pop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `loop'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'

  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `pop'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `deq'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:199:in `install_in_parallel'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:166:in `install'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:80:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli/update.rb:55:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:221:in `update'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
  /usr/local/bin/bundle:22:in `load'
  /usr/local/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.10
Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
GEM_HOME  /Users/shirleykabir/Desktop/RealBootstrap/vendor/bundle/ruby/2.4.0
GEM_PATH  
Git       2.10.1 (Apple Git-78)
Platform  x86_64-darwin-15
OpenSSL   OpenSSL 1.0.2j  26 Sep 2016
```

## Bundler settings

```
frozen
  Set for your local app (/Users/shirleykabir/Desktop/RealBootstrap/.bundle/config): "1"
path
  Set for your local app (/Users/shirleykabir/Desktop/RealBootstrap/.bundle/config): "vendor/bundle"
disable_shared_gems
  Set for your local app (/Users/shirleykabir/Desktop/RealBootstrap/.bundle/config): "true"
```

### LINKED ISSUE #5526: fatal: No live threads left. Deadlock? with Ruby 2.3.0,bundler-1.14.6
Hi,
I face this issue with my bundle install.
/zserver/ruby/bin/bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this
machine.
Fetching gem metadata from http://rubygems.org/.......
Fetching version metadata from http://rubygems.org/..
Fetching dependency metadata from http://rubygems.org/.
Your lockfile was created by an old Bundler that left some things out.
You can fix this by adding the missing gems to your Gemfile, running bundle install, and then removing the gems from your Gemfile.
The missing gems are:
* echoe depended upon by prawn-format
Using rake 10.3.2
Using i18n 0.6.9
Using multi_json 1.10.1
Using builder 3.0.4
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using hike 1.2.3
Using tilt 1.4.1
Using mime-types 1.25.1
Using polyglot 0.3.5
Using arel 3.0.3
Using tzinfo 0.3.39
Using coffee-script-source 1.7.0
Using execjs 2.2.0
Using json 2.0.3
Using thor 0.19.1
Using docile 1.1.5
Using simplecov-html 0.8.0
Using tins 1.3.0
Using daemon_controller 1.2.0
Using daemons 1.1.9
Using diff-lcs 1.2.5
Using flexmock 0.9.0
Using libv8 3.16.14.3 (x86_64-linux)
Using libxml-ruby 2.7.0
Using machinist 2.0
Using memcache-client 1.8.5
Using mysql2 0.3.16
Using prawn-core 0.5.0.1
Using prawn-layout 0.2.0.1
Using bundler 1.14.6
Using rb-readline 0.5.1
Using ref 1.0.5
Using rspec-core 2.99.1
Using rspec-mocks 2.99.1
Using ruby-ole 1.2.11.7
Using rubyzip 1.0.0
Using sass 3.3.8
Using hoe 3.12.0
Using faker 1.3.0
Using activesupport 3.2.18
Using rack-cache 1.2
Using rack-test 0.6.2
Using rack-ssl 1.3.4
Using sprockets 2.2.2
Using rest-client 1.6.7
Using treetop 1.4.15
Using coffee-script 2.2.0
Using rdoc 3.12.2
Using uglifier 2.5.1
Using simplecov 0.8.2
Using term-ansicolor 1.3.0
Using passenger 4.0.45
Using rspec-expectations 2.99.1
Using therubyracer 0.12.1
Using spreadsheet 0.6.9
Using zip-zip 0.3
Using test-unit 1.2.3
Using activemodel 3.2.18
Using delayed_job 4.0.1
Using mail 2.5.4
Using coveralls 0.7.0
Using rspec-collection_matchers 1.0.0
Using actionpack 3.2.18
Using activerecord 3.2.18
Using activeresource 3.2.18
Using actionmailer 3.2.18
Using railties 3.2.18
Using delayed_job_active_record 4.0.1
Using coffee-rails 3.2.2
Using jquery-rails 3.1.1
Using rails 3.2.18
Using rspec-rails 2.99.0
Using sass-rails 3.2.6
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/zserver/ruby/bin/bundle install`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
fatal: No live threads left. Deadlock?
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `pop'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `deq'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:199:in `install_in_parallel'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:166:in `install'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:80:in `run'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/install.rb:70:in `run'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:181:in `block in install'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/settings.rb:99:in `temporary'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:180:in `install'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /zserver/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
  /zserver/ruby/bin/bundle:22:in `load'
  /zserver/ruby/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
GEM_HOME  /opt/tarantula/rails/vendor/bundle/ruby/2.3.0
GEM_PATH  
Git       1.7.1
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1e 11 Feb 2013
```

## Bundler settings

```
frozen
  Set for your local app (/opt/tarantula/rails/.bundle/config): "1"
path
  Set for your local app (/opt/tarantula/rails/.bundle/config): "vendor/bundle"
disable_shared_gems
  Set for your local app (/opt/tarantula/rails/.bundle/config): true
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Any help?
Regards,
AN

### LINKED ISSUE #5529: No live threads left. Deadlock?
Using rake 12.0.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.10.1
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.5
Using mime-types-data 3.2016.0521
Using arel 6.0.4
Using public_suffix 2.0.5
Using net-ssh 4.0.1
Using awesome_print 1.7.0
Using bcrypt 3.1.11
Using debug_inspector 0.0.2
Using byebug 9.0.6
Using capistrano-harrow 0.5.3
Using puma 3.6.2
Using chartkick 2.2.2
Using climate_control 0.1.0
Using coderay 1.1.1
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using thor 0.19.4
Using concurrent-ruby 1.0.4
Using connection_pool 2.2.1
Using orm_adapter 0.5.0
Using unf_ext 0.0.7.2
Using multipart-post 2.0.0
Using jwt 1.5.6
Using little-plugger 1.1.4
Using multi_json 1.12.1
Using memoist 0.15.0
Using os 0.9.6
Using httpclient 2.8.3
Using hurley 0.2
Using uber 0.0.15
Using retriable 2.1.0
Using tilt 2.0.5
Using hashie 3.4.6
Using localtunnel 1.0.3
Using netrc 0.11.0
Using method_source 0.8.2
Using mimemagic 0.3.2
Using multi_xml 0.6.0
Using mysql2 0.3.21
Using nested_form 0.3.2
Using bundler 1.14.3
Using slop 3.6.0
Using rails-assets-angular 1.6.1
Using remotipart 1.3.1
Using sass 3.4.23
Using rdoc 4.3.0
Using redis 3.3.2
Using table_print 1.5.6
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.7.0.1
Using rack-test 0.6.3
Using warden 1.2.6
Using rack-protection 1.5.3
Using mime-types 3.1
Using addressable 2.5.0
Using net-scp 1.2.1
Using binding_of_caller 0.7.2
Using cocaine 0.5.8
Using coffee-script 2.4.1
Using uglifier 3.0.4
Using sprockets 3.7.1
Using unf 0.1.4
Using faraday 0.10.1
Using logging 2.1.0
Using representable 2.3.0
Using haml 4.0.7
Using omniauth 1.3.1
Using pry 0.10.4
Using rails-assets-angular-devise 1.3.0
Using sdoc 0.4.2
Using turbolinks 5.0.1
Using activesupport 4.2.1
Using loofah 2.0.3
Using rack-pjax 1.0.0
Using sidekiq 4.2.9
Using sinatra 1.4.8
Using mail 2.6.4
Using sshkit 1.11.5
Using domain_name 0.5.20161129
Using signet 0.7.3
Using oauth2 1.3.0
Using wit-ruby 0.0.2
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.7
Using activemodel 4.2.1
Using groupdate 3.2.0
Using jbuilder 2.6.1
Using spring 2.0.0
Using rails-html-sanitizer 1.0.3
Using airbrussh 1.1.2
Using http-cookie 1.0.3
Using googleauth 0.5.1
Using omniauth-oauth2 1.4.0
Using rails-dom-testing 1.0.8
Using activejob 4.2.1
Using activerecord 4.2.1
Using paperclip 5.0.0
Using protected_attributes 1.1.3
Using capistrano 3.7.1
Using rest-client 2.0.0
Using google-api-client 0.9.20
Using omniauth-facebook 4.0.0
Using actionview 4.2.1
Using capistrano-bundler 1.2.0
Using capistrano-rvm 0.1.2
Using capistrano3-nginx 2.1.5
Using capistrano3-puma 1.2.1
Using messenger-ruby 1.1.3 from git://github.com/xyz.git (at master@abc)
Using google_drive 2.1.2
Using actionpack 4.2.1
Using capistrano-rails 1.2.1
Using actionmailer 4.2.1
Using railties 4.2.1
Using kaminari 0.17.0
Using sprockets-rails 3.2.0
Using coffee-rails 4.1.1
Using responders 2.3.0
Using font-awesome-rails 4.7.0.1
Using jquery-rails 4.2.2
Using jquery-ui-rails 5.0.5
Using rails 4.2.1
Using sass-rails 5.0.6
Using web-console 2.3.0
Using devise 3.5.10
Using ngannotate-rails 1.2.2
Using rails_admin 1.1.1
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/usr/local/bin/bundler `

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/ISSUES.md?**

  ...

## Backtrace

```
fatal: No live threads left. Deadlock?
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `pop'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `deq'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer.rb:199:in `install_in_parallel'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer.rb:166:in `install'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer.rb:80:in `run'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/installer.rb:24:in `install'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli/install.rb:70:in `run'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:181:in `block in install'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/settings.rb:99:in `temporary'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:180:in `install'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/exe/bundler:4:in `load'
  /var/lib/gems/2.3.0/gems/bundler-1.14.3/exe/bundler:4:in `<top (required)>'
  /usr/local/bin/bundler:23:in `load'
  /usr/local/bin/bundler:23:in `<main>'
```

## Environment

```
Bundler   1.14.3
Rubygems  2.6.10
Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
GEM_HOME  /var/lib/gems/2.3.0
GEM_PATH  /var/lib/gems/2.3.0:/home/ajr/.gem/ruby/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all
Git       2.7.4
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.2g  1 Mar 2016
```

## Bundler settings

```
git.allow_insecure
  Set for the current user (/home/ajr/.bundle/config): "true"
jobs
  Set for your local app (/home/ajr/Documents/zippytest/.bundle/config): "1"
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

### LINKED ISSUE #5549: Bundle install deadlock
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/usr/local/bin/bundle install`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
fatal: No live threads left. Deadlock?
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `pop'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/worker.rb:43:in `deq'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:199:in `install_in_parallel'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:166:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:80:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/install.rb:70:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:181:in `block in install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/settings.rb:99:in `temporary'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:180:in `install'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
  /usr/local/bin/bundle:22:in `load'
  /usr/local/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.11
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
GEM_HOME  /usr/local/bundle
GEM_PATH
Git       2.1.4
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1t  3 May 2016
```

## Bundler settings

```
disable_shared_gems
  Set for your local app (/usr/local/bundle/config): true
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
```

--- TEMPLATE END ----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5378.
Closes #5480.
Closes #5519.
Closes #5526.
Closes #5529.
Closes #5549.
Closes https://github.com/bundler/bundler/issues/5572.

Not the ideal fix (the error message could be more helpful in pointing out which issue is being faced), but overall better than deadlocking.

### CODE REVIEW

**Comment by indirect** [comment]
Looks good 👍 @bundlerbot r+

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
I'll rebase and fix the tests as soon as I get a chance

**Comment by segiddins** [comment]
@indirect please review

File: lib/bundler/shared_helpers.rb [hunk 1]
```diff
@@ -152,6 +152,24 @@ def trap(signal, override = false, &block)
       end
     end
 
+    def ensure_same_dependencies(spec, old, new)
+      new = new.reject {|d| d.type == :development }
```
Comment (colby-swandale) [inline lib/bundler/shared_helpers.rb]: this is very nickpicky but can we not call it `new`? It just makes me think that you're initialising a new object

Comment (segiddins) [inline lib/bundler/shared_helpers.rb]: `old_deps`, `new_deps` sound better?

**Comment by segiddins** [comment]
(╯°□°）╯︵ ┻━┻ old rubygems printing the type in `Dependency#to_s` strikes again

File: lib/bundler/shared_helpers.rb (hunk 1 above)
Comment (colby-swandale) [inline lib/bundler/shared_helpers.rb]: yes! thank you!

**Comment by segiddins** [comment]
This is passing, r?

**Comment by colby-swandale** [comment]
I tried to validate this using:

Gemfile:
```
source "https://rubygems.org"
gem "rspec"
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)

PLATFORMS
  ruby

DEPENDENCIES
  rspec

BUNDLED WITH
   1.14.6
```

I removed a few deps from the Gemfile.lock:
```
       rspec-core (~> 3.5.0)
       rspec-expectations (~> 3.5.0)
       rspec-mocks (~> 3.5.0)
-    rspec-core (3.5.4)
-      rspec-support (~> 3.5.0)
     rspec-expectations (3.5.0)
       diff-lcs (>= 1.2.0, < 2.0)
       rspec-support (~> 3.5.0)
```

But i am continue to get the Deadlock:
```
fatal: No live threads left. Deadlock?
2 threads, 2 sleeps current:0x0000000135d6c0 main thread:0x0000000135d6c0
* #<Thread:0x00000001391f10 sleep_forever>
   rb_thread_t:0x0000000135d6c0 native:0x007f7870943700 int:0
   /bundler/bundler/lib/bundler/worker.rb:43:in `pop'
   /bundler/bundler/lib/bundler/worker.rb:43:in `deq'
   /bundler/bundler/lib/bundler/installer/parallel_installer.rb:132:in `process_specs'
   /bundler/bundler/lib/bundler/installer/parallel_installer.rb:103:in `call'
   /bundler/bundler/lib/bundler/installer/parallel_installer.rb:77:in `call'
   /bundler/bundler/lib/bundler/installer.rb:199:in `install_in_parallel'
   /bundler/bundler/lib/bundler/installer.rb:166:in `install'
   /bundler/bundler/lib/bundler/installer.rb:80:in `run'
   /bundler/bundler/lib/bundler/installer.rb:24:in `install'
   /bundler/bundler/lib/bundler/cli/install.rb:70:in `run'
   /bundler/bundler/lib/bundler/cli.rb:187:in `block in install'
   /bundler/bundler/lib/bundler/settings.rb:100:in `temporary'
   /bundler/bundler/lib/bundler/cli.rb:186:in `install'
   /bundler/bundler/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
   /bundler/bundler/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
   /bundler/bundler/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
   /bundler/bundler/lib/bundler/cli.rb:21:in `dispatch'
   /bundler/bundler/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
   /bundler/bundler/lib/bundler/cli.rb:11:in `start'
   bundler/exe/bundle:35:in `block in <main>'
   /bundler/bundler/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
   bundler/exe/bundle:27:in `<main>'
* #<Thread:0x00000001d739c0@Parallel Installer Worker #0@/bundler/bundler/lib/bundler/worker.rb:89 sleep_forever>
   rb_thread_t:0x000000020e83a0 native:0x007f786bed3700 int:0
   /bundler/bundler/lib/bundler/worker.rb:56:in `pop'
   /bundler/bundler/lib/bundler/worker.rb:56:in `block in process_queue'
   /bundler/bundler/lib/bundler/worker.rb:55:in `loop'
   /bundler/bundler/lib/bundler/worker.rb:55:in `process_queue'
   /bundler/bundler/lib/bundler/worker.rb:89:in `block (2 levels) in create_threads'

  /bundler/bundler/lib/bundler/worker.rb:43:in `pop'
  /bundler/bundler/lib/bundler/worker.rb:43:in `deq'
  /bundler/bundler/lib/bundler/installer/parallel_installer.rb:132:in `process_specs'
  /bundler/bundler/lib/bundler/installer/parallel_installer.rb:103:in `call'
  /bundler/bundler/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /bundler/bundler/lib/bundler/installer.rb:199:in `install_in_parallel'
  /bundler/bundler/lib/bundler/installer.rb:166:in `install'
  /bundler/bundler/lib/bundler/installer.rb:80:in `run'
  /bundler/bundler/lib/bundler/installer.rb:24:in `install'
  /bundler/bundler/lib/bundler/cli/install.rb:70:in `run'
  /bundler/bundler/lib/bundler/cli.rb:187:in `block in install'
  /bundler/bundler/lib/bundler/settings.rb:100:in `temporary'
  /bundler/bundler/lib/bundler/cli.rb:186:in `install'
  /bundler/bundler/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /bundler/bundler/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /bundler/bundler/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
  /bundler/bundler/lib/bundler/cli.rb:21:in `dispatch'
  /bundler/bundler/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
  /bundler/bundler/lib/bundler/cli.rb:11:in `start'
  bundler/exe/bundle:35:in `block in <main>'
  /bundler/bundler/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  bundler/exe/bundle:27:in `<main>'
```

Let me know if i'm not doing something correctly 👍

**Comment by segiddins** [comment]
The lockfiles weren't corrupted in that particular way (they just had missing dependencies, _not_ entire specs removed that still had dependencies elsewhere)

**Comment by colby-swandale** [comment]
i figured 😄  I'm trying to recreate the bug so i can test this using the Gemfiles from the reported issues but replicating it is proving it difficult.

This looks good too btw 👍

**Comment by segiddins** [comment]
No worries, I ended up fixing that case anyways ;)

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
@bundlerbot r+

**Comment by segiddins** [comment]
> Starting to get worried about the growing bucket of options that gets passed to for, but this looks good! 👍

It'll get better once we can use named parameters
