### PR TITLE
Fix GEM_PATH regression in 1.13.

### LINKED ISSUE #4592: Could not find 'bundler'
Software
  * osx 10.11.4
  * rbenv 1.0.0
  * ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
  * Rails 4.2.6

bundle exec gem list|grep guard

    guard (2.13.0)
    guard-compat (1.2.1)
    guard-rspec (4.6.5)

bundle exec guard -d

    RubyDep: WARNING: Your Ruby has security vulnerabilities! (To disable warnings, set RUBY_DEP_GEM_SILENCE_WARNINGS=1)
    RubyDep: WARNING: Your Ruby is: 2.2.3 (insecure). Recommendation: install 2.2.5 or 2.3.1. (Or, at least to 2.2.4 or 2.3.0)
    00:54:56 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
    00:54:56 - DEBUG - Notiffany: growl not available (Please add "gem 'growl'" to your Gemfile and run your app with "bundle exec".).
    00:54:56 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
    00:54:56 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin15.4.0").
    00:54:56 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin15.4.0").
    00:54:56 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin15.4.0").
    00:54:56 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
    00:54:56 - DEBUG - Notiffany: emacs not available (Emacs client failed).
    00:54:56 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
    00:54:56 - DEBUG - Notiffany: file not available (No :path option given).
    00:54:56 - DEBUG - Notiffany is using TerminalTitle to send notifications.
    00:54:56 - DEBUG - Command execution: hash stty
    00:54:56 - DEBUG - Guard starts all plugins
    00:54:56 - DEBUG - Hook :start_begin executed for Guard::RSpec
    00:54:56 - INFO - Guard::RSpec is running
    00:54:56 - DEBUG - Hook :start_end executed for Guard::RSpec
    00:54:56 - INFO - Guard is now watching at '/Users/lemon/Documents/chavis'
    00:54:56 - DEBUG - Start interactor
    00:54:56 - DEBUG - Command execution: stty -g 2>/dev/null
    [1] guard(main)>
    00:54:58 - DEBUG - Interactor was stopped or killed
    00:54:58 - DEBUG - Command execution: stty  2>/dev/null
    00:54:58 - INFO - Run all
    00:54:58 - DEBUG - Hook :run_all_begin executed for Guard::RSpec
    00:54:58 - INFO - Running all specs
    /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 98 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=/Users/lemon/Documents/chavis/vendor/bundle/ruby/2.2.0', execute `gem env` for more information
    	from /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    	from /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    	from /Users/lemon/.rbenv/versions/2.2.3/bin/bundle:22:in `<main>'
    00:54:58 - ERROR - Failed: "bundle exec rspec -f progress -r /Users/lemon/Documents/chavis/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.6.5/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec" (exit code: 1)

    00:54:58 - DEBUG - Start interactor
    00:54:58 - DEBUG - Command execution: stty -g 2>/dev/null
gem env

    RubyGems Environment:
      - RUBYGEMS VERSION: 2.4.5.1
      - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin15]
      - INSTALLATION DIRECTORY: /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
      - RUBY EXECUTABLE: /Users/lemon/.rbenv/versions/2.2.3/bin/ruby
      - EXECUTABLE DIRECTORY: /Users/lemon/.rbenv/versions/2.2.3/bin
      - SPEC CACHE DIRECTORY: /Users/lemon/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: /Users/lemon/.rbenv/versions/2.2.3/etc
      - RUBYGEMS PLATFORMS:
        - ruby
        - x86_64-darwin-15
      - GEM PATHS:
         - /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
         - /Users/lemon/.gem/ruby/2.2.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
         - :sources => ["https://gems.ruby-china.org/"]
      - REMOTE SOURCES:
         - https://gems.ruby-china.org/
      - SHELL PATH:
         - /Users/lemon/.rbenv/versions/2.2.3/bin
         - /usr/local/Cellar/rbenv/1.0.0/libexec
         - /Users/lemon/.rbenv/shims
         - /usr/local/bin
         - /usr/bin
         - /bin
         - /usr/sbin
         - /sbin

https://github.com/guard/guard-rspec/issues/369

### LINKED ISSUE #4974: Regression in disable_shared_gems behavior
Between the versions `v1.13.0.pre.1` and `v1.13.0.rc1` the behavior of `bundle install --deployment` has changed concerning the `disable_shared_gems` flag. Gems that are present in system rubygems are no longer installed into the local gems folder (`vendor/bundle`).

This behavior seems to be caused by change in `Bundler#configure_gem_path` of

    ENV["GEM_PATH"] = ""

to

    env["GEM_PATH"] = nil

introduced in commit 9a8ab67da6567c767307e8861893761542483ba0

I tested under 2.4.5.1 rubygems version.

I am sorry If that new behavior is an intended one and not a regression.

### PR DESCRIPTION
**Pull request by chrismo**
_nth time is a charm ... here's the latest latest latest commit message_:

Fix disable_shared_gems bug & keep nested exec
tl;dr `--deployment` will copy _all_ gems to the `--path` now and a
proper fix is in place for nested bundle execs when `--path` is set and
RubyGems >=2.6.2 is being used.

Fixes #4974.

There's two problems blended in here. Let's trace the events here from
the beginning, shall we?

First off, from probably the first versions of Bundler, when
`disable_shared_gems` is true, the `GEM_PATH` gets internally overridden
and initialized to an empty string. This is done to make sure that later
in the `Bundler.setup` process it's expanded to ONLY the Bundler `--path`
setting, otherwise it expands to include the system path.

In 1.12, `bundle exec` was changed to use `Kernel.load` in some cases,
and that new code path calls `require "bundler/setup"`.

Later, issue #4592 was filed, showing that in cases like `--deployment`
where `disable_shared_gems` is true, Bundler couldn't find itself,
because Bundler never lives in the `--path` but only in system gems. And
as it would later be discovered, was not a problem with RubyGems 2.6.1,
but was a problem with >=2.6.2 (and older RubyGems it would seem, though
those weren't as thoroughly investigated).

We fixed #4592 (see PR #4701) in 1.13.0 by changing the oooold code
initializing `GEM_PATH` to be initialized to `nil` instead of empty
string in all `disable_shared_gems` cases. But it created another bug,
filed as #4974, wherein system gems were no longer copied to the
`--path` when `disable_shared_gems` is true. In this commit here (#4992)
we've reverted the change so that `GEM_PATH` is now back to being
initialized to an empty string instead of `nil`.

That fixes #4974, but regresses #4592, and we needed a new way to fix
it.

After a few tortured attempts at this, I ran across issue #4602, a
similar report of nested bundle execs being broken, #4602 itself an
extension of #4381 reporting the same problem. It brought to light the
role the Rubygems version played in the problem.

When the `bundler` gem is installed and the wrapper is generated for any
gem executables, the contents of this wrapper are determined by the
Rubygems version. Up until RubyGems 2.6.1 the last line of this wrapper
calls `Gem.bin_path`. Bundler replaces the Rubygems implementation of
`Gem.bin_path` with its own, and has for a long time made a special
exception for the Bundler gem itself, short-circuiting with the contents
of a special ENV variable called `BUNDLE_BIN_PATH`.

In Rubygems 2.6.2, `bin_path` was superseded by a new
`Gem.activate_bin_path` method which did what `bin_path` did but also
activated the gem. Bundler 1.13 added support for this, but it didn't
include the same short-circuit for bundler itself. (Alert user @taoza
even noticed this here
fcaab35#r56665282).

This commit also includes that short circuit for Rubygems >=2.6.2 now
and nested bundle exec should continue to work.

### CODE REVIEW

File: lib/bundler/cli/exec.rb [hunk 1]
```diff
@@ -81,6 +82,38 @@ def kernel_load(file, *args)
       abort "#{e.class}: #{e.message}\n  #{backtrace.join("\n  ")}"
     end
 
+    # This is pretty damned esoteric. Since the dawn of Bundler, when
```
Comment (segiddins) [inline lib/bundler/cli/exec.rb]: please remove the `damned`

File: lib/bundler/cli/exec.rb [hunk 2]
```diff
@@ -81,6 +82,38 @@ def kernel_load(file, *args)
...
+    #
+    # We fixed this in 1.13.0 by removing GEM_PATH ever being set to
+    # empty string, and that fixed bundle exec and broke `--deployment`.
+    # So much for trusting a test suite. (shrug) I should know better.
+    #
+    # So, we're putting back the age-old empty string, and coping for
+    # the weirdness right here, with this method and its appropriate
+    # 27-to-1 ratio of doc lines to code lines.
+    def fixup_gem_path_env
+      ENV['GEM_PATH'] = nil if Bundler.settings[:disable_shared_gems]
```
Comment (segiddins) [inline lib/bundler/cli/exec.rb]: double quotes

File: lib/bundler/cli/exec.rb (hunk 1 above)
Comment (chrismo) [inline lib/bundler/cli/exec.rb]: Yes, sorry - it was late at night.

File: lib/bundler/cli/exec.rb (hunk 2 above)
Comment (chrismo) [inline lib/bundler/cli/exec.rb]: Yeah, I forgot to run rubocop, though I knew this wasn't done yet - no tests.

**Comment by chrismo** [comment]
yeah, tests for the bundle exec, and tests for the disable_shared_gems putting _all_ gems into the --path, which said tests would have prevented this change in the first place.

**Comment by indirect** [comment]
@chrismo awesomeeeeee thank you for tracking this down :bow: I'm very excited to get this fixed once we have tests. :)

**Comment by chrismo** [comment]
due credit to @miros for isolating the problem commit in #4974 in the first place

**Comment by chrismo** [comment]
The comments were a bit rambly and late-night stream of consciousness. Re-wrote them to try and be clearer.

Still need to research `bundle exec` tests -- there's actually plenty of coverage in spec/install/path_spec.rb, I don't know why CI continues to pass those specs when locally they clearly fail for me when the bug is in play.

**Comment by chrismo** [comment]
This isn't working. I still can't get any spec within the bundler codebase itself to reliably recreate the problem, because it's a nested bundle exec that is the original problem ... and that's just a bit too bizarre for my brain to figure out. 

The spec_helper calls `Spec::Rubygems.setup` which sets up the `PATH` to be:

      ENV["PATH"] = ["#{Path.root}/exe", "#{Path.system_gem_path}/bin", ENV["PATH"]].join(File::PATH_SEPARATOR)

placing the local exe/bundle in the PATH, thwarting any attempt to recreate a nested bundle exec accurately which IRL needs to be hitting the Rubygems generated bin entry:

```
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'
# ...snip...
load Gem.activate_bin_path('bundle', 'bundle', version)
```

So. I at least created [this bundler-case](https://github.com/chrismo/bundler-cases/blob/master/cases/issues/bundler-4592/bundler-4592.rb) based on the original #4592 bug report. This accurately shows the nested bundle exec problem in 1.12.5 and the fix in 1.13.1.

But the code HERE in this PR (#4992) - while it fixes #4974, it regresses the nested bundle exec fix (#4592).

The reason is also due to the nature of the 1.12.5 change to use Kernel.load (same process, I think) instead of Kernel.exec (forks a new process). There's so much global state (and a lot of it memoized) that's setup in `require "bundler/setup"` -- I can't find a way to create a workaround to fix up the pathing. It gets easily as complicated as the above situation just trying to recreate a failing spec. (Very happy to be wrong here, btw).


So so.

IMO, #4974 is a much worse problem than #4592. #4974 keeps `--deployment` from working properly (unless none of your bundled gems are installed as system gems). #4592 only breaks nested bundle exec only in a `--path` install situation. 

I'd rather release a 1.13.2 with #4974 fixed and intentionally regress #4592 until we can figure out how to properly support the nested `bundle exec` case.

**Comment by chrismo** [comment]
proactive code review - I'm being a little sloppy on this PR, I'll rebase and remove the version change that snuck in and everything before for realz. Just pushing for comment on the substantive parts.

File: lib/bundler/cli/exec.rb [hunk 3]
```diff
@@ -81,6 +82,34 @@ def kernel_load(file, *args)
...
+    #
+    # We fixed this (the bundle exec bug) in 1.13.0 by changing GEM_PATH to be
+    # initialized to nil instead of empty string in all cases. But it created
+    # another bug. We've reverted the change so that GEM_PATH is now back to
+    # being initialized, but still need to override how the GEM_PATH is set
+    # in this special case so that the bundler executable can be found.
+    def configure_gem_path_override
+      if Bundler.settings[:disable_shared_gems]
+        # TODO MODO hate this spooky at a distance global state voodoo
+        ENV["DO_NOT_LIMIT_GEM_PATH"] = "true"
```
Comment (segiddins) [inline lib/bundler/cli/exec.rb]: any reason this couldn't just check if `ENV["GEM_PATH"].nil?`

File: spec/commands/exec_spec.rb [hunk 4]
```diff
@@ -591,4 +592,26 @@ def bin_path(a,b,c)
...
+    let(:system_gems_to_install) { super() << :bundler }
+    before do
+      gemfile <<-G
+        source "file://#{gem_repo1}"
+        gem "rack"
+      G
+      bundle :install, :system_bundler => true, :path => "vendor/bundler"
+    end
+
+    it "works with disable_shared_gems" do
```
Comment (segiddins) [inline spec/commands/exec_spec.rb]: needs a more descriptive name

File: lib/bundler/cli/exec.rb (hunk 3 above)
Comment (chrismo) [inline lib/bundler/cli/exec.rb]: this `configure_gem_path_override` method is now called _before_ `require "bundler/setup"` ... prior commit had me attempting to undo something that was done inside bundler/setup _after_ it was called ... had to change the approach since it was too late at that point.

**Comment by chrismo** [comment]
Ok, I think this ready, presuming CI passes.

**Comment by indirect** [comment]
@segiddins all your requested changes appear to be addressed in the final commit, even though they're still shown in the PR... is that normal? this seems sub-optimal. :/

**Comment by chrismo** [comment]
dunno - prior versions of github, before the code review stuff, used to collapse comments on old commits. i'm not used to the new review flow ... maybe @segiddins needs to "sign off" on his comments in some way?

**Comment by indirect** [comment]
yeah, I guess so. well, I'm happy with this, so @homu r+.

**Comment by chrismo** [comment]
shoot. i also built a bundler-cases for this - and it's still failing. argh. looking ...

**Comment by indirect** [comment]
heh. well, in that case... @homu r-

**Comment by indirect** [comment]
@homu r=chrismo

@chrismo when you're ready, you can approve this for testing and merging with the comment `r+` directed at homu. once that's done, I'd like to release 1.13.2.

**Comment by indirect** [comment]
...dammit, I can't remember the bot's syntax.

@homu r-
@homu delegate=chrismo

**Comment by indirect** [comment]
@homu r-

**Comment by chrismo** [comment]
bah, keep forgetting that one test I'd added that's still failing. fixing, new commit shortly

**Comment by chrismo** [comment]
@homu retry

**Comment by chrismo** [comment]
@homu r+

**Comment by chrismo** [comment]
@homu retry

**Comment by indirect** [comment]
ffffuuuu, sorry @chrismo

@homu retry

**Comment by chrismo** [comment]
whew. and don't come back :)
