### PR TITLE
Fix bundle lock when default gemfile is present

### LINKED ISSUE #6460: If `Gemfile.lock` exists, `bundle lock --lockfile=<path>` does not do what you expect
On a project with an existing `Gemfile.lock`, when I run

```bash
bundle lock --lockfile=AlternativeGemfile.lock
```

I get the output

```
Fetching gem metadata from https://rubygems.org/.........
Writing lockfile to /home/deivid/Code/nipanipa/AlternativeGemfile.lock
```

However, no `AlternativeGemfile.lock` file is actually written.

If I remove the `Gemfile.lock` file, then things work as I expect.

### PR DESCRIPTION
**Pull request by agrim123**
Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

The problem was on running `bundle lock --lockfile=AlternativeGemfile.lock` if a default lockfile already exists then `AlternativeGemfile.lock` is not created.

### What was your diagnosis of the problem?

My diagnosis was that the [lock](https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L340) function does not check the file but for contents, so a new file is not created in case of an existing lockfile.

### What is your fix for the problem, implemented in this PR?

My fix was to check for the file existence.

Closes #6460

### CODE REVIEW

File: spec/commands/lock_spec.rb [hunk 1]
```diff
@@ -97,6 +97,14 @@ def read_lockfile(file = "Gemfile.lock")
     expect { read_lockfile }.to raise_error(Errno::ENOENT)
   end
 
+  it "writes to custom location using --lockfile when a default lockfile is present", :focus do
```
Comment (segiddins) [inline spec/commands/lock_spec.rb]: please remove the `:focus`

Comment (agrim123) [reply spec/commands/lock_spec.rb]: Done.

**Comment by segiddins** [comment]
@bundlerbot r+
