### PR TITLE
[CLI::Lock] Fail gracefully when updating a missing gem

### LINKED ISSUE #5693: Bundler 1.15 breaks on `bundle lock --update <gem>` for newly added gems
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out why things are going wrong.

- **What did you do?**

  Repro:

  ```
  bundle init
  echo 'gem "redis"' >> Gemfile
  bundle lock --update redis
  echo 'gem "statsd-ruby"' >> Gemfile
  bundle lock --update statsd-ruby
  ```

  (Note that the specific gems do not seem to matter. I picked these randomly for repro.)

- **What did you expect to happen?**

  I expected Bundler to add `statsd-ruby` to the `Gemfile.lock`, as it was able to do in v1.14.6.

- **What happened instead?**

  Instead, what happened was this error template.

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried downgrading to v1.14.6, which worked as expected.

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

  Yes.

## Backtrace

```
RuntimeError: Unable to find a spec satisfying statsd-ruby in the set. Perhaps the lockfile is corrupted?
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/spec_set.rb:39:in `block in for'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/spec_set.rb:24:in `loop'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/spec_set.rb:24:in `for'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/definition.rb:113:in `initialize'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/dsl.rb:200:in `new'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/dsl.rb:200:in `to_definition'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/dsl.rb:12:in `evaluate'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/definition.rb:33:in `build'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler.rb:129:in `definition'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli/lock.rb:26:in `run'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli.rb:527:in `lock'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli.rb:20:in `dispatch'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli.rb:10:in `start'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/exe/bundle:35:in `block in <top (required)>'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.15.0/exe/bundle:27:in `<top (required)>'
  /Users/cainlevy/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
  /Users/cainlevy/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler   1.15.0
Rubygems  2.5.1
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
GEM_HOME  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
GEM_PATH  /Users/cainlevy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0:/Users/cainlevy/.gem/ruby/2.3.0
Git       2.11.0 (Apple Git-81)
Platform  x86_64-darwin-16
OpenSSL   OpenSSL 1.0.2j  26 Sep 2016
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/cainlevy/.bundle/config): "minitest"
gem.mit
  Set for the current user (/Users/cainlevy/.bundle/config): "false"
gem.coc
  Set for the current user (/Users/cainlevy/.bundle/config): "true"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'redis'
gem 'statsd-ruby'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    redis (3.3.3)

PLATFORMS
  ruby

DEPENDENCIES
  redis

BUNDLED WITH
   1.15.0
```

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5693 by behaving the same way `bundle update` handles gems that aren't in the lockfile

### CODE REVIEW

File: lib/bundler/cli/lock.rb [hunk 1]
```diff
@@ -22,7 +22,15 @@ def run
       Bundler::Fetcher.disable_endpoint = options["full-index"]
 
       update = options[:update]
-      update = { :gems => update, :lock_shared_dependencies => options[:conservative] } if update.is_a?(Array)
+      if update.is_a?(Array) # unlocking specific gems
+        # cycle through the requested gems, to make sure they exist
```
Comment (colby-swandale) [inline lib/bundler/cli/lock.rb]: I would prefer if this block was in a method

Comment (segiddins) [inline lib/bundler/cli/lock.rb]: should I change it in update as well?

Comment (colby-swandale) [inline lib/bundler/cli/lock.rb]: Awesome if want to but it's not a show stopper to getting 1.15.1 out the door.

**Comment by indirect** [comment]
Huh, I had no idea that the lock flag accepted arguments 😬 this looks good to me 👍

**Comment by segiddins** [comment]
@colby-swandale done, r?

**Comment by colby-swandale** [comment]
thank you! 🎉  @bundlerbot r+
