### PR TITLE
Fix `bundle outdated` with `--patch` and/or `--minor` for non-semantically versioned gems

### LINKED ISSUE #4438: Running `bundle outdated --patch` gets NoMethodError: undefined method '>' for nil:NilClass
- What did you do?

  I ran the command `/Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle outdated --patch`

- What did you expect to happen?

  I expected Bundler to give me all the gems which were outdated at the patch level.

- What happened instead?

  Part of the way through the output of the command, I got a `NoMethodError`.

Error details

    NoMethodError: undefined method `>' for nil:NilClass
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:139:in `update_present_via_semver_portions'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:60:in `block in run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:45:in `each'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli/outdated.rb:45:in `run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:257:in `outdated'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:11:in `start'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/exe/bundle:27:in `block in <top (required)>'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/connor/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.0.rc/exe/bundle:19:in `<top (required)>'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `load'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/bundle:22:in `<main>'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /Users/connor/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment

```
  Bundler   1.12.0.rc
  Rubygems  2.6.2
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  GEM_HOME  /Users/connor/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/connor/.rvm/gems/ruby-2.3.0:/Users/connor/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.8.1
  rubygems-bundler (1.4.4)
      
  Bundler settings
      
  build.eventmachine
    Set for the current user (/Users/connor/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
  build.charlock_holmes
    Set for the current user (/Users/connor/.bundle/config): "--with-icu-dir=/usr/local/opt/icu4c"
  jobs
    Set for your local app (/Users/connor/Programming/gitlab-development-kit/gitlab/.bundle/config): "4"
  without
    Set for your local app (/Users/connor/Programming/gitlab-development-kit/gitlab/.bundle/config): "mysql:production"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/connor/.rvm/gems/ruby-2.3.0/bin:/Users/connor/.rvm/gems/ruby-2.3.0@global/bin:/Users/connor/.rvm/rubies/ruby-2.3.0/bin:/Users/connor/.rvm/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/usr/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/connor/.rvm/gems/ruby-2.3.0:/Users/connor/.rvm/gems/ruby-2.3.0@global"
```

#### Reproduction steps
Assuming Bundler 1.12.0.rc, Git, and Ruby 2.3.0 (note that I tested on 2.1.8 as well and it crashes the same way) are installed:

- `git clone https://gitlab.com/gitlab-org/gitlab-ce.git`
- `cd gitlab-ce`
- `git checkout 091c77e3c54b15fa2378a89d15400795dc9f91ee`
- `bundle install` - you may want to/have to link eventmachine with your OpenSSL version from Homebrew if on OS X.
- `bundle outdated --patch`

If the above doesn't reproduce the error, I can give you the full script for setting up GitLab Development Kit that includes Postgres, Redis, etc. but it's (probably) not necessary to reproduce this. A shallow clone of GitLab CE *should* produce the same error while also downloading faster, but it won't give you the same exact commit for reproduction purposes should the `Gemfile.lock` change at all.

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- Examples of non-semantic versions: "7.0", "8", [`gitlab_meta` versioning](https://rubygems.org/gems/gitlab_meta/versions/7.0)
- Closes #4438

### CODE REVIEW

File: spec/commands/outdated_spec.rb [hunk 1]
```diff
@@ -244,6 +246,7 @@
   shared_examples_for "version update is detected" do
     it "reports that a gem has a newer version" do
       subject
+      expect(out).to_not include("ERROR REPORT TEMPLATE")
```
Comment (segiddins) [inline spec/commands/outdated_spec.rb]: Please use positive expectations instead

Comment (RochesterinNYC) [inline spec/commands/outdated_spec.rb]: Hm, I was following precedence here (https://github.com/bundler/bundler/blob/master/spec/bundler/friendly_errors_spec.rb#L29 and https://github.com/bundler/bundler/blob/master/spec/install/gemfile/path_spec.rb#L161). There isn't any consistent output that would be generated after the `Outdated gems included in the bundle:` portion that can be relied on.

**Comment by segiddins** [comment]
Because this is using an index we've built up in the specs, the output should be completely deterministic

**Comment by RochesterinNYC** [comment]
@segiddins Yup, I added positive assertions based on presence of `"Outdated gems included in the bundle:"` and `"Bundle up to date!"`.

**Comment by indirect** [comment]
@RochesterinNYC awesome, thanks!

@homu r+

**Comment by indirect** [comment]
Hmm we have --patch and --minor in 1.12, right? We should backport this.

**Comment by segiddins** [comment]
@indirect I can `.rc.4`?

**Comment by indirect** [comment]
@segiddins yes please, thank you!

**Comment by RochesterinNYC** [comment]
Are there any pressing, outstanding issues related to features/things added in 1.12.0?
