### PR TITLE
[Installer] Load plugin files from path gems

### LINKED ISSUE #5429: RubyGems post-install hook not triggering
I see a lot of talk about Bundler install hooks on different issues/PRs that (like this thread) mentions that Bundler respects RubyGems post install hooks, but I'm testing it out and that doesn't seem to be the case… if I install via `gem install` the hook runs, but if I add the gem to a Gemfile and install it doesn't seem to be triggering the hook. Is that unexpected?

### PR DESCRIPTION
**Pull request by segiddins**
Closes #5429 .

Because RubyGems doesn't know about path gems before we install, we need to manually load the plugin files for the path gems we're installing. This is basically copying the logic RG uses, but scoped only to those gems that we're entirely responsible for.

### CODE REVIEW

File: lib/bundler/installer.rb [hunk 1]
```diff
@@ -162,13 +162,23 @@ def generate_standalone_bundler_executable_stubs(spec)
...
       jobs = [Bundler.settings[:jobs].to_i - 1, 1].max if can_install_in_parallel?
       install_in_parallel jobs, options[:standalone], force
     end
 
+    def load_plugins
+      Bundler.rubygems.load_plugins
+
+      requested_path_gems = @definition.requested_specs.select {|s| s.source.is_a?(Source::Path) }
+      path_plugin_files = requested_path_gems.map do |spec|
+        spec.matches_for_glob("rubygems_plugin#{Bundler.rubygems.suffix_pattern}")
```
Comment (segiddins) [inline lib/bundler/installer.rb]: failing on RG < 1.8

**Comment by segiddins** [comment]
This ought to pass now

**Comment by segiddins** [comment]
Fixed

**Comment by indirect** [comment]
@bundlerbot r+
