### PR TITLE
Dsl#with_source should restore the previous source

### LINKED ISSUE #3974: Git reference inside a source block changes .lock file unexpectedly
If you reference a git repo inside of a source block, any gems after said git reference will be changed in `Gemfile.lock`.  

##### Starting project, with the `Gemfile` and `Gemfile.lock` as expected:
https://github.com/craig-day/bearded-nemesis

I have the base gems for a simple rails app in my `Gemfile`, then I also want to use https://rails-assets.org for my asset management, so I added a source block at the bottom to do so.  All is fine and behaving expectedly. 

##### Example problem branch: 
https://github.com/craig-day/bearded-nemesis/tree/broken_gemfile

This example seems like a silly thing to do, but it illustrates the point well. I added a gem with a git reference to the source block.  If you look at the diff for `Gemfile.lock` ([here](https://github.com/craig-day/bearded-nemesis/compare/broken_gemfile)) you will notice that it removed the `!` from all of the gems referenced after the git reference. 

To put this into context, I can explain a real situation.  At work we use a private gem server to host published gems, and Github to manage our git repos. In the normal situation, gems will get published to the gem server and all is well. If I want to test a gem feature branch for example, the simplest thing to do would be to tell that gem to reference the branch on Github.  This works fine, but it makes unnecessary changes to the lock file. I would expect referencing git to only change the single gem I changed.

### PR DESCRIPTION
**Pull request by agis-**
Fixes #3974.

### CODE REVIEW

File: spec/realworld/edgecases_spec.rb [hunk 1]
```diff
@@ -210,4 +210,21 @@
...
+        source 'https://rails-assets.org' do
+          gem 'rails-assets-angular', git: "git@github.com:sharoo/rails-assets-angular.git"
+          gem "i18n"
+        end
+      G
+
+      expect(out).to include("Could not find gem 'i18n' in rubygems repository https://rails-assets.org")
+      expect(exitstatus).to eq(7) if exitstatus
+    end
+  end
```
Comment (agis-) [inline spec/realworld/edgecases_spec.rb]: This could also be tested inside `Dsl` but a realworld test is more suitable for such a bug imho. That said, I'm not happy with the fact that we depend on `rails-assets.org` being up *and* not containing `i18n`. Ideas?

cc @indirect @segiddins

File: lib/bundler/dsl.rb [hunk 2]
```diff
@@ -230,12 +230,13 @@ def add_git_sources
 
     def with_source(source)
       if block_given?
+        old_source = @source
```
Comment (segiddins) [inline lib/bundler/dsl.rb]: Needs to go outside the conditional

File: lib/bundler/dsl.rb [hunk 3]
```diff
@@ -230,12 +230,13 @@ def add_git_sources
...
         @source = source
         yield
       end
       source
     ensure
-      @source = nil
+      @source = old_source || nil
```
Comment (segiddins) [inline lib/bundler/dsl.rb]: The `||` is unnecessary

**Comment by segiddins** [comment]
Awesome catch! Id actually prefer to see this covered by just a normal test as well, there are some helpers for setting up sources.

**Comment by agis-** [comment]
@segiddins Yep that was my thought in https://github.com/bundler/bundler/pull/3978#discussion_r38821336. Cool, I'll do it.

**Comment by agis-** [comment]
@segiddins Updated!

File: lib/bundler/dsl.rb [hunk 4]
```diff
@@ -229,13 +229,14 @@ def add_git_sources
...
     def with_source(source)
+      old_source = @source
       if block_given?
         @source = source
         yield
       end
       source
     ensure
-      @source = nil
+      @source = old_source
```
Comment (grosser) [inline lib/bundler/dsl.rb]: man what an obvious bug :(

**Comment by grosser** [comment]
:+1:

File: lib/bundler/dsl.rb (hunk 4 above)
Comment (agis-) [inline lib/bundler/dsl.rb]: yep :)

**Comment by indirect** [comment]
awesome, thanks!

@homu r+

**Comment by TimMoore** [comment]
Good catch!
