### PR TITLE
Use the full expanded path of passed `Gemfile` during `eval_gemfile`

### LINKED ISSUE #4584: Bundler fails to parse a gemspec line when it appears in a gemfile that is evaled inside of another gemfile
Bundler version: 1.12.4
OS: observed on OS X 10.10.5 AND on Ubuntu 14.04.1
Description:
Bundler fails to parse a gemspec line when it appears in a gemfile that is evaled inside of another gemfile
Reproducing: The minimum setup for reproducing this bug can be found in the simple example at https://github.com/stupakov/bundler-bug

Failure output:

```
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile-other`: No such file or directory - gems/mygem/mygem.gemspec. Bundler cannot continue.

 #  from Gemfile-other:1
 #  -------------------------------------------
 >  gemspec path: 'gems/mygem'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /Users/myusername/workspace/bundler-bug/Gemfile:1
 #  -------------------------------------------
 >  eval_gemfile 'Gemfile-other'
 #  -------------------------------------------
```

### PR DESCRIPTION
**Pull request by RochesterinNYC**
- fixes #4584

### CODE REVIEW

**Comment by segiddins** [comment]
So if we're accidentally trying to support eval_gemfile we probably should restore `@gemfile` in an `ensure`?

**Comment by RochesterinNYC** [comment]
Ah, as in there are things in the class that count on `@gemfile` being a non-absolute path?

**Comment by segiddins** [comment]
No I mean after the nested gemfile is eval'd we're back in the original gemfile.

**Comment by RochesterinNYC** [comment]
Ah, gotcha. Added that to the PR. Good call.

File: lib/bundler/dsl.rb [hunk 1]
```diff
@@ -34,7 +34,9 @@ def initialize
     end
 
     def eval_gemfile(gemfile, contents = nil)
-      @gemfile = Pathname.new(gemfile)
+      expanded_gemfile_path = Pathname.new(gemfile).expand_path
+      @original_gemfile ||= expanded_gemfile_path
```
Comment (segiddins) [inline lib/bundler/dsl.rb]: This should just be `original_gemfile = @gemfile`, no need for an ivar

Comment (RochesterinNYC) [inline lib/bundler/dsl.rb]: Initially, I thought that we wanted to restore `@gemfile` to the original, top-level `Gemfile` path after each `eval_gemfile` invocation. However, you're right, I think if we want to support multiple, recursive nesting of `eval_gemfile` invocations, we have to restore `@gemfile` to the Gemfile path specified for the recursive level above each `eval_gemfile` call. This way, if people are doing things like chaining > 2 Gemfiles and `eval_gemfile` calls (I hope not though...), `@gemfile` is set properly on each recursive level.

File: lib/bundler/dsl.rb [hunk 2]
```diff
@@ -34,7 +34,9 @@ def initialize
     end
 
     def eval_gemfile(gemfile, contents = nil)
-      @gemfile = Pathname.new(gemfile)
+      expanded_gemfile_path = Pathname.new(gemfile).expand_path
+      @gemfile = expanded_gemfile_path
+      original_gemfile = @gemfile
```
Comment (segiddins) [inline lib/bundler/dsl.rb]: these two lines are backwards, no?

Comment (RochesterinNYC) [inline lib/bundler/dsl.rb]: Yes, you're right. I think what this is telling me is that we need a spec specifically to cover this case. Though, I can't really think of a functionally useful test case. As in, a test with multiple Gemfiles that emulates a real-world use case. If you know any off the top of your head, let me know. Otherwise, I'll look around Github/think one up.

**Comment by RochesterinNYC** [comment]
Added an integration spec covering the `@gemfile` restoration code change.

**Comment by segiddins** [comment]
Yay! 👍 
@homu r+
