### PR TITLE
Always use source credentials

### LINKED ISSUE #3297: When credentials are configured for a source, use them unconditionally
Right now (as of 1.7.9), it tries to make an unauthenticated request first, then retries with authentication if the first request fails.

This causes issues on some gem servers. For example, Gemfury supports the dependency API and allows a mix of public and private gems in the same repository. It does not forbid unauthenticated requests, but it returns partial information.

See discussion on #3180, #3260 and #3296.

### PR DESCRIPTION
**Pull request by TimMoore**
Previously, it tried to make an unauthenticated request first, then retried with authentication if the first request failed.

This causes issues on some gem servers. For example, Gemfury supports the dependency API and allows a mix of public and private gems in the same repository. It does not forbid unauthenticated requests, but it returns partial information.

Now configured credentials are always used.

Fixes #3297, #3296, #3180.

### CODE REVIEW

**Comment by TimMoore** [comment]
If you came here looking to test this fix, here's what you need to do:

```
git clone https://github.com/TimMoore/bundler.git`
cd bundler
git checkout issue-3297-always-use-source-credentials
rake install
```

That will install it to your system gems. Alternatively, you can create a `dbundle` alias as described in [the `DEVELOPMENT.md` guide](https://github.com/bundler/bundler/blob/master/DEVELOPMENT.md#development-setup) to run it from source.

Thanks!

**Comment by arronmabrey** [comment]
I will try and set aside some time later today and test this out.

File: lib/bundler/fetcher.rb [hunk 1]
```diff
@@ -374,35 +371,35 @@ def bundler_cert_store
...
+    def resolve_remote_uri(uri)
+      add_configured_credentials(Bundler::Source.mirror_for(uri))
     end
 
-  private
+    def add_configured_credentials(uri)
+      auth = Bundler.settings[uri.to_s]
+      if auth
+        uri = uri.dup
+        uri.user, uri.password = *auth.split(":", 2)
```
Comment (TimMoore) [inline lib/bundler/fetcher.rb]: Hmm... I just realised that this will now make credentials in config override ones in the `Gemfile`.

We never really clearly defined what would happen when you have both, but in the past I suppose it would have tried the ones in the `Gemfile`, then fail immediately if the original ones didn't work (it got a 401 or 403 response).

I guess, intuitively, I would expect that the ones in the `Gemfile` would override the ones in config, but what do other people think?

Comment (indirect) [inline lib/bundler/fetcher.rb]: I would expect ENV, then Gemfile, then config file, myself, I think? But I’m not positive.

Comment (TimMoore) [inline lib/bundler/fetcher.rb]: Hmm, yeah well right now ENV and config file are normalised to a single settings object.

**Comment by will** [comment]
It works for me

```
➤ bundler version
Bundler version 1.7.3
➤ bundle update 
Fetching source index from https://redacted.s3.amazonaws.com/redacted/
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/........
Resolving dependencies...
Using …
Your bundle is updated!


➤ gem install bundler
➤ bundle version
Bundler version 1.7.11
➤ bundle update 
Authentication is required for https://redacted.s3.amazonaws.com/redacted/.
Please supply credentials for this source. You can do this by running:
 bundle config https://redacted.s3.amazonaws.com/redacted/ username:password


➤ dbundle version
Bundler version 1.7.11-dev
# I edited version.rb to add -dev to be sure
➤ dbundle update
Fetching source index from https://redacted.s3.amazonaws.com/redacted/
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/........
Resolving dependencies...
Using …
Your bundle is updated!
```

File: lib/bundler/fetcher.rb (hunk 1 above)
Comment (indirect) [inline lib/bundler/fetcher.rb]: Since ENV and config file are combined, let’s make them lower priority than the in-Gemfile credentials.

**Comment by indirect** [comment]
Hooray! Thanks for all your work on this, @TimMoore.

**Comment by arronmabrey** [comment]
:tada: @TimMoore :tada:

File: lib/bundler/fetcher.rb (hunk 1 above)
Comment (TimMoore) [inline lib/bundler/fetcher.rb]: OK with the code as merged I think it's the other way around. I raised a new issue for that: #3343

**Comment by dpiddy** [comment]
Thanks! Looking forward to 1.7.12 being released with this fix.

**Comment by indirect** [comment]
1.7.12 is released!
