### PR TITLE
Restrict gemspec platforms without breaking windows

### LINKED ISSUE #4150: Bundler 1.11.0 break rspec on Windows (only windows), because #4114
It's very strange, but I can isolate problem to bundler, #4114 

```
c:\git\Rails\wechat>rake
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/r
spec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spe
c.rb'
No DRb server is running. Running in local process instead ...

Randomized with seed 51044
........................................................................................................................
.................................................

Finished in 0.65787 seconds (files took 10.4 seconds to load)
169 examples, 0 failures

Randomized with seed 51044


c:\git\Rails\wechat>bundle check
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to t
he latest version of Bundler by running `gem install bundler`.
Resolving dependencies...
The Gemfile's dependencies are satisfied

c:\git\Rails\wechat>gem update
Updating installed gems
Updating bundler
Fetching: bundler-1.11.0.gem (100%)
Successfully installed bundler-1.11.0
Gems updated: bundler

c:\git\Rails\wechat>rake
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/r
spec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spe
c.rb'
No DRb server is running. Running in local process instead ...
c:/git/Rails/wechat/spec/lib/wechat/access_token_spec.rb:3:in `<top (required)>': uninitialized constant Wechat (NameErr
or)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_
spec_files'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_file
s'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:70:in `rescue in run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:66:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/r
spec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spe
c.rb' failed

c:\git\Rails\wechat>
```

### PR DESCRIPTION
**Pull request by smellsblue**
This keeps the fix for #4102 but also fixes #4150

I added a test which fails if #4102 is broken, but also fails if #4150 is broken.

I have run the specs in the following scenarios:
* With the original Bundler code: the JRuby spec breaks but the Windows one passes
* With my previous fix attempt: the JRuby spec passes but the Windows one breaks
* With this new fix: both pass

### CODE REVIEW

File: lib/bundler/dsl.rb [hunk 1]
```diff
@@ -218,6 +219,14 @@ def method_missing(name, *args)
 
   private
 
+    def gem_helpers
```
Comment (segiddins) [inline lib/bundler/dsl.rb]: why is this necessary?

Comment (smellsblue) [inline lib/bundler/dsl.rb]: @segiddins this is to get access to the `generic` method for use as: `gem_helpers.generic(Gem::Platform.local)`. Without turning the platform into a generic platform, you might get something like `"x86_64-linux"` which doesn't exist in the reverse platform map.

I was also contemplating including the `Bundler::GemHelpers` module in the `Bundler::Dsl` class, but that would mean exposing the `generic` method as a public method as part of the DSL, which seemed wrong to me. I opted for the private method to avoid this.

Another thing I was thinking of would be to use another object that already includes `Bundler::GemHelpers` to call `generic` on that, but I don't know which object the DSL has access to that includes the module. Are you aware of such an object so I could nix this method?

Comment (segiddins) [inline lib/bundler/dsl.rb]: What about throwing a `module_function` at the top of `GemHelpers` and calling it directly?

Comment (smellsblue) [inline lib/bundler/dsl.rb]: Yup! That makes sense, working on a commit now. Thanks!

**Comment by smellsblue** [comment]
@segiddins What do you think of 1d7f8093616724bde3efec714eec51021fecca56? I opted against making `generic` a `module_function` since it would make it private (though there seems to be no references to it where this would be a problem, so let me know if you prefer that). I'll get back later tonight to resolve the new conflicts.

**Comment by segiddins** [comment]
I'd personally prefer `module_function`

**Comment by smellsblue** [comment]
@segiddins I changed it to module_function, and rebased on top of the new master

**Comment by segiddins** [comment]
👍🏻

**Comment by Eric-Guo** [comment]
work like a charm :accept:

**Comment by segiddins** [comment]
@indirect r+?

**Comment by Eric-Guo** [comment]
I tested this PR several days, so far so good. Thanks @smallsblue

**Comment by indirect** [comment]
@homu r+
