### PR TITLE
Rescue ArgumentError and explain the security vulnerability. Fixes #4726

### LINKED ISSUE #4726: Rescue and explain failed `remove_entry_secure`
As revealed by #4722, sometimes `FileUtils.remove_entry_secure` will raise an error like this one:

> ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/home/user/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160626-2788-14mnsu2" (parent directory mode 40777)

We need to catch this error and explain that it is a security vulnerability to allow your home directory to be world-writable. We should also explain the fix (which is probably (?) to run `chmod o-w ~`). There is a longer description of the times when the error can be raised in the [FileUtils#remove_entry_secure docs](http://ruby-doc.org/stdlib-2.1.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-remove_entry_secure), and a very slightly longer description of the vulnerability at [Mitre](http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2005-0448).

### PR DESCRIPTION
**Pull request by allenzhao**
Ref #4726 
Might need to add a spec?
/c @indirect @RochesterinNYC

### CODE REVIEW

File: lib/bundler.rb [hunk 1]
```diff
@@ -195,6 +195,16 @@ def tmp(name = Process.pid.to_s)
 
     def rm_rf(path)
       FileUtils.remove_entry_secure(path) if path && File.exist?(path)
+    rescue ArgumentError => e
+      if /world writeable/ =~ e.message
```
Comment (segiddins) [inline lib/bundler.rb]: why not check the permission bits on the parent directory before trying to remove it instead of rescuing the exception?

Comment (allenzhao) [inline lib/bundler.rb]: Actually, when I searched google for this, Nanoc changed remove_entry_secure to rm_rf (See https://github.com/nanoc/nanoc/commit/aeb71156d6a97851f9f262ae68eb09074432b314 and https://github.com/nanoc/nanoc/issues/465).  
But since we're using remove_entry_secure, I think it's better to throw the error and warn our user about the global-writable issue.

Comment (segiddins) [inline lib/bundler.rb]: agree, but I'd rather we check for the error condition ourselves rather than checking for a regex match on the thrown exceptions message

Comment (allenzhao) [inline lib/bundler.rb]: You mean check the permission of home directory?

Comment (segiddins) [inline lib/bundler.rb]: yes

**Comment by segiddins** [comment]
@allenzhao ping on this?

**Comment by allenzhao** [comment]
Will deliver a updated version today :)

Samuel Giddins <notifications@github.com>于2016年7月14日周四 下午10:57写道：

> @allenzhao <https://github.com/allenzhao> ping on this?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/bundler/bundler/pull/4738#issuecomment-232690249>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADLBfAHi_hMEjvv4iYsEXpKB94jbvaLJks5qVk5BgaJpZM4JCKuL>
> .
>
-- 
Should you have any question, please contact me by replying to this email
or using the contact info below.

Cheers,
Allen
-------------------------------------------------------------
*赵泽涵  |  Allen Zhao*

清华大学 /  经济管理学院管理科学与工程系 / 管理科学与工程硕士 2015级

MSc in Management Science and Engineering
Department of Management Science and Engineering, School of Economics and
Management
Tsinghua University, Beijing, P.R.China

Tel:+86 18501959574
微信Wechat: cnallenzhao
E-mail: i@allenzhao.com / cnallenzhao@gmail.com
--------------------------------------------------------------
This message is a private communication. The information contained in this
message or attached to this communication may be protected from disclosure
and may contain information that is legally privileged, proprietary, and/or
confidential. If you are not the intended recipient, please do not read,
copy, use, or disclose it to others. Please notify the sender of the
delivery error by replying to this message, and then delete it and any
attachments from your system. Thank you.
-------------------------------------------------------------

**Comment by allenzhao** [comment]
Spec tests have passed.
@segiddins r?

File: lib/bundler.rb [hunk 2]
```diff
@@ -196,6 +196,14 @@ def tmp(name = Process.pid.to_s)
...
     def rm_rf(path)
       FileUtils.remove_entry_secure(path) if path && File.exist?(path)
+    rescue ArgumentError
+      message = <<EOF
+It is a security vulnerability to allow your home directory to be world-writable, and bundler can not continue.
+You should probably consider fixing this issue by running `chmod o-w ~` on *nix.
+Please refer to http://ruby-doc.org/stdlib-2.1.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-remove_entry_secure for details.
+EOF
+      Bundler.ui.warn(message) if File.expand_path(path).world_writable?
+      raise
```
Comment (segiddins) [inline lib/bundler.rb]: This will still cause the error template to be shown

**Comment by segiddins** [comment]
I'm not seeing any added tests in the PR

**Comment by segiddins** [comment]
@allenzhao ping on this?

**Comment by allenzhao** [comment]
@segiddins I'm still working on the spec test part

**Comment by allenzhao** [comment]
@segiddins @RochesterinNYC 
Please review ;)

File: lib/bundler.rb [hunk 3]
```diff
@@ -196,6 +196,13 @@ def tmp(name = Process.pid.to_s)
 
     def rm_rf(path)
       FileUtils.remove_entry_secure(path) if path && File.exist?(path)
+    rescue ArgumentError
+      message = <<EOF
+It is a security vulnerability to allow your home directory to be world-writable, and bundler can not continue.
+You should probably consider fixing this issue by running `chmod o-w ~` on *nix.
+Please refer to http://ruby-doc.org/stdlib-2.1.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-remove_entry_secure for details.
+EOF
+      File.world_writable?(path) ? Bundler.ui.warn(message) : raise
```
Comment (segiddins) [inline lib/bundler.rb]: This still needs to raise an error since removing the directory has failed

**Comment by allenzhao** [comment]
@segiddins @RochesterinNYC 
Please kindly review again :)

**Comment by indirect** [comment]
Looks good to me. 👍 @segiddins r?

**Comment by segiddins** [comment]
@homu r+

**Comment by segiddins** [comment]
@homu retry

**Comment by allenzhao** [comment]
@homu retry
