### PR TITLE
Fix Github username for README.md contrib URL

### LINKED ISSUE #5438: Invalid Github URL in README
Bundler version 1.14.3

With using
```
bundle gem example
```
The `README.md` file under contributions shows as:

```
https://github.com/Daniel P. Clark/example
```

This is taken from `git config --get user.name` (I believe)

The command that should be used is `git config --get github.user` which would result in:

```
https://github.com/danielpclark/example
```

### PR DESCRIPTION
**Pull request by danielpclark**
This fixes #5438 where the wrong git config variable was being
retrieved.

This was using `git config user.name` rather than `git config github.user` in URL in `README.md`

### CODE REVIEW

File: lib/bundler/cli/gem.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def run
       constant_name = name.gsub(/-[_-]*(?![_-]|$)/) { "::" }.gsub(/([_-]+|(::)|^)(.|$)/) { $2.to_s + $3.upcase }
       constant_array = constant_name.split("::")
 
-      git_user_name = `git config user.name`.chomp
+      git_user_name = `git config github.user`.chomp
```
Comment (segiddins) [inline lib/bundler/cli/gem.rb]: Can we rename to GitHub username?

Comment (danielpclark) [inline lib/bundler/cli/gem.rb]: I'm working on it

File: spec/commands/newgem_spec.rb [hunk 2]
```diff
@@ -116,19 +119,20 @@ def gem_skeleton_assertions(gem_name)
...
         expect(bundled_app("test_gem/README.md").read).not_to include("[USERNAME]")
+        expect(bundled_app("test_gem/README.md").read).to include("github.com/bundleuser")
       end
     end
 
-    context "git config user.name is absent" do
+    context "git config gihhub.user is absent" do
       before do
-        `git config --unset user.name`
+        `git config --unset github.user`
```
Comment (segiddins) [inline spec/commands/newgem_spec.rb]: `sys_exec("git config --unset github.user")`

File: spec/commands/newgem_spec.rb [hunk 3]
```diff
@@ -116,19 +119,20 @@ def gem_skeleton_assertions(gem_name)
...
       end
 
       it "contribute URL set to git username" do
         expect(bundled_app("test_gem/README.md").read).not_to include("[USERNAME]")
+        expect(bundled_app("test_gem/README.md").read).to include("github.com/bundleuser")
       end
     end
 
-    context "git config user.name is absent" do
+    context "git config gihhub.user is absent" do
```
Comment (segiddins) [inline spec/commands/newgem_spec.rb]: can we please also keep a test that runs with `user.name` unset?

Comment (segiddins) [inline spec/commands/newgem_spec.rb]: `github`

Comment (danielpclark) [inline spec/commands/newgem_spec.rb]: That's already accounted for 4 times.

https://github.com/danielpclark/bundler/blob/54de051a2e24bddefa85bbb1ffadadacd6800f2d/spec/commands/newgem_spec.rb#L56 ,
https://github.com/danielpclark/bundler/blob/54de051a2e24bddefa85bbb1ffadadacd6800f2d/spec/commands/newgem_spec.rb#L67 ,
https://github.com/danielpclark/bundler/blob/54de051a2e24bddefa85bbb1ffadadacd6800f2d/spec/commands/newgem_spec.rb#L253 , https://github.com/danielpclark/bundler/blob/54de051a2e24bddefa85bbb1ffadadacd6800f2d/spec/commands/newgem_spec.rb#L543

File: spec/commands/newgem_spec.rb (hunk 2 above)
Comment (danielpclark) [inline spec/commands/newgem_spec.rb]: This exact syntax with `git` is used 5 times in this file.  Is there a new policy written somewhere for this change to be enacted?

Comment (olleolleolle) [inline spec/commands/newgem_spec.rb]: @danielpclark The cool thing about `sys_exec` is that in `spec_helpers/support.rb` it is defined like this:

```ruby
    def sys_exec(cmd)
      Open3.popen3(cmd.to_s) do |stdin, stdout, stderr, wait_thr|
        yield stdin, stdout, wait_thr if block_given?
        stdin.close

        @exitstatus = wait_thr && wait_thr.value.exitstatus
        @out = Thread.new { stdout.read }.value.strip
        @err = Thread.new { stderr.read }.value.strip
      end

      (@all_output ||= String.new) << [
        "$ #{cmd.to_s.strip}",
        out,
        err,
        @exitstatus ? "# $? => #{@exitstatus}" : "",
        "\n",
      ].reject(&:empty?).join("\n")

      @out
    end
    bang :sys_exec

```

As you can see, some of the noteworthy output-management makes easily-checkable, standardized strings out of the I/O.

There are other helper methods for specs that check that standardized output.

So, using `sys_exec` smooths the path for the RSpec usage in the project.

Comment (danielpclark) [inline spec/commands/newgem_spec.rb]: @olleolleolle Alright, that sounds reasonable.  Is it cool if I modify all 5 lines in this file from back-ticks to this as a second commit?  Or should I keep the scope of the PR just to my changes.

Comment (olleolleolle) [inline spec/commands/newgem_spec.rb]: @danielpclark Here is my take. Code collaboration is difficult, at all times, and it's not interactive, and we all have to wait on each other. Timezones and life and everything. But we can do it!

To get _this_ change merged: focus on the immediate feedback.

If you only change the file where you _have_ to, a second, clean-up-only PR with only "go from backticks to `sys_exec` everywhere in this file" could be a way to get this fix (and the next one) quicker to "done".

Keep changes easy to review.

_Good luck, and thanks for doing this!_

**Comment by olleolleolle** [comment]
@danielpclark Oh, the `gihhub.user` typo is still in there.

**Comment by danielpclark** [comment]
@olleolleolle Got it.

**Comment by segiddins** [comment]
Thanks so much!
@bundlerbot r+
