### PR TITLE
Replace locked gem sources with Gemfile equivalents.

### LINKED ISSUE #3585: Gem found in multiple sources
I had a similar problem as reported in #3378, and it appears to come up when a gem from the primary source depends on a gem from a custom source. For example, `stripe-ruby-mock` depends on `stripe`, and even when the `source` is specified for the `stripe` gem, Bundler is giving the "found in multiple sources" error.

Here's a quick demo to reproduce this. Note: if you have the `stripe` gem installed, you'll have to uninstall it in order to get the error message.

```bash
# if necessary, uninstall stripe gem
gem uninstall stripe

mkdir bundler-test && cd bundler-test
echo "source 'https://rubygems.org'"                   >> Gemfile
echo "gem 'json'"                                      >> Gemfile
echo "gem 'stripe', source: 'https://code.stripe.com'" >> Gemfile
echo "gem 'stripe-ruby-mock'"                          >> Gemfile
bundle install
```

This produces the following output:

```
Fetching source index from https://code.stripe.com/
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.....
Fetching version metadata from https://rubygems.org/..
Fetching source index from https://code.stripe.com/
Using blankslate 3.1.3
Using dante 0.2.0
Using unf_ext 0.0.7.1
Using unf 0.1.4
Using domain_name 0.5.24
Using http-cookie 1.0.2
Using multi_json 1.11.0
Using rack 1.6.0
Using mime-types 2.4.3
Using netrc 0.10.3
Using rest-client 1.8.0
Using jimson-temp 0.9.5
Using json 1.8.2
Installing stripe 1.20.1
Using stripe-ruby-mock 2.1.1
Using bundler 1.9.4
Bundle complete! 3 Gemfile dependencies, 16 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'stripe' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * https://code.stripe.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'stripe', :source => 'https://rubygems.org/'
Then uninstall the gem 'stripe' (or delete all bundled gems) and then install again.
```

This is on OS X 10.9 with Ruby 2.2.2 (p95) and Bundler 1.9.4.

Notes:
* The `json` gem is present as it seemed to be necessary to trigger the error message, possibly indicating a problem with mixed `source`s in gems in a dependency hierarchy (`stripe-ruby-mock` depends on `stripe` depends on `json`).
* Running `bundle install` again does not report an error. (Not a problem necessarily, just an observation for trying to reproduce this.)
* The error seemingly only appears on a fresh install (when `bundler` is the only installed gem prior to running `bundle install`) or when all of the gems in my example are installed except for `stripe`.

### PR DESCRIPTION
**Pull request by TimMoore**
Previously, an up-to-date lock file would retain the aggregate gem
source on all dependencies, so if the gems were not installed locally,
you'd get an ambiguous gem warning and possibly the wrong source
selected.

Fixes #3585

### CODE REVIEW

File: lib/bundler/definition.rb [hunk 1]
```diff
@@ -184,11 +184,10 @@ def specs_for(groups)
     # @return [SpecSet] resolved dependencies
     def resolve
       @resolve ||= begin
+        last_resolve = converge_locked_specs
```
Comment (TimMoore) [inline lib/bundler/definition.rb]: Moving this out is a bigger behavioural change than I would have liked, but it was the smallest code change I could work out. All of the tests pass (locally)... is there anything else this could break?

Comment (indirect) [inline lib/bundler/definition.rb]: I think you're right. Now that we have sources (and don't save those sources in the lock), we have to resolve the sources using the Gemfile even when it's frozen/locked/etc.
