### PR TITLE
Safely store concurrent compact index downloads

### LINKED ISSUE #4519: Concurrent bundle install runs raise errors unlinking ~/.bundle/cache/compact_index/rubygems.org.443.[..]/versions
- What did you do?

  I ran the command `bundle install` in four parallel processes using different RVM gemsets (therefore different GEM_HOME), but under the same user account with a shared HOME environment variable.  No Gemfile.lock was present, it was a clean checkout of a project with only a Gemfile.

- What did you expect to happen?

  I expected Bundler to complete without error by either locking the files it's downloading to be safer with multiple processes, or to use caches that are unique per GEM_HOME.

- What happened instead?

  Instead, what actually happened was one of the `bundle install` commands failed intermittently (a very small percentage of the time) with an error deleting `~/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.

  It appears that the compact index cache is shared for a whole user account without any locking, so multiple processes can try to download the same file at the same time and cause errors for each other.

Error details

    Errno::ENOENT: No such file or directory - /home/jenkins/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:50:in `unlink'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:50:in `delete'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:50:in `update'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/fetcher/compact_index.rb:63:in `available?'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/fetcher.rb:154:in `use_api'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/source/rubygems.rb:331:in `select'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/index.rb:10:in `build'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/source/rubygems.rb:82:in `specs'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:209:in `each'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:209:in `block in index'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/index.rb:10:in `build'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:206:in `index'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:200:in `resolve'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:140:in `specs'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/installer.rb:195:in `resolve_if_need'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/installer.rb:70:in `run'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/installer.rb:22:in `install'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/cli/install.rb:102:in `run'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/cli.rb:175:in `install'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/cli.rb:11:in `start'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/exe/bundle:27:in `block in <top (required)>'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/gems/bundler-1.12.1/exe/bundle:19:in `<top (required)>'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/bin/bundle:23:in `load'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/bin/bundle:23:in `<main>'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/bin/ruby_executable_hooks:15:in `eval'
      /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.1
  Rubygems  2.4.8
  Ruby      2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
  GEM_HOME  /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0
  GEM_PATH  /usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0:/usr/local/rvm/gems/ruby-2.0.0-p353@global
  RVM       1.26.11 (1.26.11)
  Git       1.8.3.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0/bin:/usr/local/rvm/gems/ruby-2.0.0-p353@global/bin:/usr/local/rvm/rubies/ruby-2.0.0-p353/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/usr/local/rvm/gems/ruby-2.0.0-p353@test_kafo_parsers_master_pull_request-0:/usr/local/rvm/gems/ruby-2.0.0-p353@global"

### PR DESCRIPTION
**Pull request by domcleal**
When bundler is run concurrently using the same bundle dir in $HOME,
the versions file can be updated from two processes at once. The
download has been changed to a temporary file, which is securely moved
into place over the original.

If retrying the update operation, the original file is no longer
immediately deleted and instead a full download is performed, later
overwriting the original file if successful.

If two processes are updating in parallel, this should ensure the
original file isn't corrupted and that both processes succeed.

- Fixes #4519

---

This would be useful on 1.12.x if possible, since the new caching behaviour with a shared home directory is causing the errors described in #4519.

### CODE REVIEW

**Comment by segiddins** [comment]
Could you try and add some test coverage for this?

File: lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb [hunk 1]
```diff
@@ -24,33 +26,41 @@ def initialize(fetcher)
...
-        headers["Accept-Encoding"] = "gzip"
-      end
+      Dir.mktmpdir(local_path.basename.to_s, local_path.dirname) do |local_temp_dir|
+        local_temp_path = Pathname.new(local_temp_dir).join(local_path.basename)
 
-      response = @fetcher.call(remote_path, headers)
-      return if response.is_a?(Net::HTTPNotModified)
+        # download new file if retrying
+        if retrying.nil? && local_path.file?
+          FileUtils.cp local_path, local_temp_path
```
Comment (segiddins) [inline lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb]: why is this copy necessary?

**Comment by segiddins** [comment]
These changes generally look good to me

**Comment by domcleal** [comment]
> Could you try and add some test coverage for this?

I've added a test around bundle install that emulates a concurrent modification of the cached file during the HTTP request, then verifies that a corrupt file wasn't written to disk.

**Comment by segiddins** [comment]
Awesome, thanks!
👍

File: lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb (hunk 1 above)
Comment (domcleal) [inline lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb]: It ensures the view of `local_path` is consistent through the whole process - if the etag and .size were taken of the original local_path, then it might change during execution with another parallel process.

It also ensures that when we append the response to the file that it's for the same matching content. If it had changed in the meantime then it'd be corrupt.

**Comment by segiddins** [comment]
@indirect r?

**Comment by indirect** [comment]
This looks great, thanks a lot!

**Comment by indirect** [comment]
@homu r+
