### PR TITLE
Handle invalid RubyGems config files

### LINKED ISSUE #4042: Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 3 column 4
I got below error message when I run bundle install 
 appledev093$ bundle install
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching gem metadata from https://rails-assets.org/../Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler.rb:315: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 3 column 4
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/config_file.rb:319:in `load_file'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/config_file.rb:192:in `initialize'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:324:in `new'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:324:in `configuration'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:65:in `configuration'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:88:in `sources='
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/fetcher.rb:126:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:343:in `block (2 levels) in remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:341:in `each'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:341:in `block in remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:81:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:88:in `block in materialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/bin/bundle:23:in `load'
      /usr/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.0.14
    Ruby      2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    GEM_HOME  /Users/appledev093/Projects/Labs/gitbase/Game-of-Threats/vendor/ruby/2.0.0
    GEM_PATH
    Git       2.5.2

Bundler settings

    path
      Set for your local app (/Users/appledev093/Projects/Labs/gitbase/Game-of-Threats/.bundle/config): "vendor"
    disable_shared_gems
      Set for your local app (/Users/appledev093/Projects/Labs/gitbase/Game-of-Threats/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=%28%3Cunknown%3E%29%3A+mapping+values+are+not+allowed+in+this+context+at+line+3+column+4&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

### PR DESCRIPTION
**Pull request by agis-**
Fixes #4042.

### CODE REVIEW

File: lib/bundler/rubygems_integration.rb [hunk 1]
```diff
@@ -67,6 +67,9 @@ def configuration
       Bundler.ui.error "#{e.class}: #{e.message}"
       Bundler.ui.trace e
       raise Gem::SystemExitException
+    rescue Psych::SyntaxError => e
+      raise YAMLSyntaxError.new(e, "Your RubyGems configuration file (usually located at ~/.gemrc) " \
```
Comment (segiddins) [inline lib/bundler/rubygems_integration.rb]: can we get the actual path from RubyGems?

File: spec/bundler/friendly_errors_spec.rb [hunk 2]
```diff
@@ -3,6 +3,32 @@
 require "bundler/friendly_errors"
 
 describe Bundler, "friendly errors" do
+  context "with invalid YAML in .gemrc" do
+    before do
+      File.open(Gem.configuration.config_file_name, 'w') do |f|
```
Comment (segiddins) [inline spec/bundler/friendly_errors_spec.rb]: this is in a tmpdir during the tests, right? If not, that'll clobber my config :(

File: lib/bundler/rubygems_integration.rb (hunk 1 above)
Comment (indirect) [inline lib/bundler/rubygems_integration.rb]: Yeah, let's print the actual path.

File: spec/bundler/friendly_errors_spec.rb (hunk 2 above)
Comment (agis-) [inline spec/bundler/friendly_errors_spec.rb]: Yep, for example in my case it's `/Users/agis/bundler/tmp/home/.gemrc`

Comment (indirect) [inline spec/bundler/friendly_errors_spec.rb]: Yes, the tests overwrite $HOME

File: lib/bundler/rubygems_integration.rb (hunk 1 above)
Comment (agis-) [inline lib/bundler/rubygems_integration.rb]: Yep I don't know why I didn't thought of that to begin with :P.

File: spec/bundler/friendly_errors_spec.rb (hunk 2 above)
Comment (segiddins) [inline spec/bundler/friendly_errors_spec.rb]: :+1:

**Comment by segiddins** [comment]
:+1:

File: lib/bundler/rubygems_integration.rb (hunk 1 above)
Comment (agis-) [inline lib/bundler/rubygems_integration.rb]: Unfortunately, `Psych::ParseError#file` is set to `nil`. And this error may be coming from different files:

* /etc/gemrc
* ~/.gemrc
* ENV['GEMRC']

Any ideas?

Comment (indirect) [inline lib/bundler/rubygems_integration.rb]: We should just print `Gem.configuration.config_file_name` :)

Comment (indirect) [inline lib/bundler/rubygems_integration.rb]: (Although we should say something like "The error is probably in your main configuration file, located at $FILENAME", since it might also be in one of those other files.)

Comment (agis-) [inline lib/bundler/rubygems_integration.rb]: `Gem.configuration` is the method that actually raises the `Psych::SyntaxError`, so we can't really do `Gem.configuration.config_file_name`.

Comment (indirect) [inline lib/bundler/rubygems_integration.rb]: Ugh, that's frustrating. Okay, I think saying "The error is in your RubyGems configuration, which is usually located in ~/.gemrc." is the best option we have, then.

Comment (agis-) [inline lib/bundler/rubygems_integration.rb]: > Your RubyGems configuration, which is usually located in ~/.gemrc, contains invalid YAML.

Sounds good?

**Comment by agis-** [comment]
The [test fails in 1.8](https://travis-ci.org/bundler/bundler/jobs/87589167); no error is thrown at all. I assume this has to do with Ruby 1.8 having a different engine for YAML parsing (ie. Scyth). I'm not sure why a *different* error isn't thrown however, since in 1.8.7:

```ruby
1.8.7-p374 :016 > YAML.parse_file('/Users/agis/.gemrc')
`ArgumentError: syntax error on line 0, col 9: `foo: bar: baz'
```

Should we bother at all with 1.8 or just skip the test there?

**Comment by segiddins** [comment]
@agis- yeah, make sure your YAML engine on 1.8.7 is Syck and not Psych.

**Comment by indirect** [comment]
@agis- sadly we have to at least run on 1.8.7 with Syck, so just add guards using defined? where needed and it should be okay.

**Comment by agis-** [comment]
OK, so things in 1.8.7 (Scyth) are kinda different. `bundle install` succeeds even with invalid YAML in `~/.gemrc`, even though a pretty clarifying warning is printed from RubyGems:

```shell
$ dbundle
entering...
Failed to load /Users/agis/.gemrc, syntax error on line 0, col 8: `foo: hi: fi'
Fetching gem metadata from https://rubygems.org/..entering...

Fetching version metadata from https://rubygems.org/.entering...

entering...
Installing hola_agis 0.0.1
Using bundler 1.10.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

So I'd propose to just skip the test in 1.8.7 and rescue `YamlSyntaxError` which does the job of handling Scyth & Psych for us.

**Comment by agis-** [comment]
@indirect Updated the PR according to my previous comment. /cc @segiddins

**Comment by segiddins** [comment]
@homu r+

**Comment by agis-** [comment]
@homu I guess this needs a retry.

**Comment by segiddins** [comment]
@homu retry
