### PR TITLE
Stop printing “failed to update” message when changing sources

### LINKED ISSUE #6325: `bundle update` shows incorrect message when updating git gems
If I have

```ruby
gem "decidim", git: "https://github.com/decidim/decidim"
```

And I run

```
bundle update decidim
```

And that results in `bundler` updating the locked sha1 reference in my lock file, I wouldn't expect `bundler` to display the "Bundler attempted to update decidim but its version stayed the same" message.

Is this a reasonable expectation?

### PR DESCRIPTION
**Pull request by segiddins**
### What was the end-user problem that led to this PR?

The problem was `bundle update` shows incorrect message when updating git gems

Closes #6325 

### What was your diagnosis of the problem?

My diagnosis was we need to check if the source has changed

### What is your fix for the problem, implemented in this PR?

My fix only prints the message when the source has not changed

Note that is does not yet fix the "updated the git sha" case, since the locked spec and the new spec actually share the same source object!

### CODE REVIEW

File: spec/commands/update_spec.rb [hunk 1]
```diff
@@ -421,6 +421,39 @@
     expect(the_bundle).to include_gems "thin 2.0", "rack 10.0", "rack-obama 1.0"
   end
 
+  it "will not warn when an explicitly updated git gem changes sha but not version" do
```
Comment (segiddins) [inline spec/commands/update_spec.rb]: this is the test that's failing, and I'm not 100% how to refactor to fix it

Comment (deivid-rodriguez) [reply spec/commands/update_spec.rb]: Fixed the test by saving the string representation of each source _before_ it's actually updated, so the comparison later works as expected.

**Comment by deivid-rodriguez** [comment]
@segiddins What do you think about this approach?

**Comment by indirect** [comment]
I'm happy with this :+1:

**Comment by segiddins** [comment]
Heh, cheeky ;) I like it! Thanks so much for taking this up

@bundlerbot r+
