### PR TITLE
Friendly filesystem permission errors

### LINKED ISSUE #3988: Unfortunately, an unexpected error occurred, and Bundler cannot continue
- What did you do?

  I ran the command `/home/hussein/.rvm/gems/ruby-2.2.2@prohealth/bin/bundle install --path /home/ubuntu/prohealth/shared/bundle --without development test --deployment --quiet`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/ubuntu
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler.rb:310:in `mkdir_p'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/installer.rb:332:in `create_bundle_path'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/installer.rb:54:in `run'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/installer.rb:18:in `install'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/cli/install.rb:80:in `run'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/cli.rb:157:in `install'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/cli.rb:10:in `start'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/bin/bundle:20:in `block in <top (required)>'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/bin/bundle:18:in `<top (required)>'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/bin/bundle:23:in `load'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.6
    Rubygems  2.4.5
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
    GEM_HOME  /home/ubuntu/prohealth/shared/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.25.28 (stable)
    Git       1.9.1

Bundler settings

    frozen
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "1"
    path
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "/home/ubuntu/prohealth/shared/bundle"
    without
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "development:test"
    disable_shared_gems
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "1"

### LINKED ISSUE #4009: Permission denied @ dir_s_mkdir - /var/www/travel/code/.bundle
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /var/www/travel/code/.bundle
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `each'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/settings.rb:153:in `set_key'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/settings.rb:21:in `[]='
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/settings.rb:94:in `without='
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli/install.rb:71:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `load'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `<main>'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.4
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.2.1
    GEM_PATH  /usr/local/rvm/gems/ruby-2.2.1:/usr/local/rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)

Bundler settings

    without
      Set for your local app (/var/www/travel/code/.bundle/config): "production:from:."
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
ubuntu@ip-172-31-29-207:/var/www/travel/code$ ^C
ubuntu@ip-172-31-29-207:/var/www/travel/code$ https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle&type=Issues
[1] 725
ubuntu@ip-172-31-29-207:/var/www/travel/code$ -bash: https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle: No such file or directory
^C
[1]+  Exit 127                https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle

### PR DESCRIPTION
**Pull request by agis-**
This introduces `SharedHelpers#filesystem_access` which can wrap any piece of code that makes a modification to the file system (eg. creating a directory). Doing so, results in user-friendly errors instead of the original ones (ie `Errno:EACCES`).

In the future we could (and probably should) handle more error types within `#filesystem_access`.

Closes #4009.
Closes #3988.

https://trello.com/c/OicgrmDd/102-improve-permissions-error-messages.

### CODE REVIEW

File: lib/bundler/source/rubygems.rb [hunk 1]
```diff
@@ -399,11 +403,16 @@ def fetch_gem(spec)
...
 
-        FileUtils.mkdir_p("#{download_path}/cache")
+        SharedHelpers.filesystem_access("#{download_path}/cache") do |p|
+          FileUtils.mkdir_p(p)
+        end
         Bundler.rubygems.download_gem(spec, uri, download_path)
 
         if Bundler.requires_sudo?
-          Bundler.mkdir_p "#{Bundler.rubygems.gem_dir}/cache"
+
```
Comment (segiddins) [inline lib/bundler/source/rubygems.rb]: extra line

**Comment by segiddins** [comment]
:+1: well done, @agis- !

File: lib/bundler/source/rubygems.rb (hunk 1 above)
Comment (agis-) [inline lib/bundler/source/rubygems.rb]: fixed

**Comment by agis-** [comment]
@robinboening I've cherry-picked (and slightly updated) your test case: https://github.com/bundler/bundler/commit/2e9f04d22725a4800460a091f3e880a99f150bf7.

I hope you don't mind :) Thanks!

**Comment by robinboening** [comment]
:+1: perfect – and I am sorry I did not notice that you have assigned yourself on that trello card already.

**Comment by segiddins** [comment]
@homu r+
