### PR TITLE
Adapt helper path regex to also work with Windows paths

### LINKED ISSUE #6892: [Windows test failure] rspec ./spec/cache/gems_spec.rb:99 # bundle cache when there is a built-in gem uses builtin gems when installing to system gems
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next one(s) (following 3 have similar output):

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec ./spec/cache/gems_spec.rb:99
Run options:
  include {:locations=>{"./spec/cache/gems_spec.rb"=>[99]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

bundle cache
  when there is a built-in gem

$ C:/Ruby24-x64/bin/ruby.exe -rrubygems -S gem --backtrace generate_index
Generating Marshal quick index gemspecs for 64 gems
................................................................
Complete
Generated Marshal quick index gemspecs: 0.163s
Generating specs index
Generated specs index: 0.002s
Generating latest specs index
Generated latest specs index: 0.002s
Generating prerelease specs index
Generated prerelease specs index: 0.001s
Compressing indices
Compressed indices: 0.009s
C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:22: warning: constant ::Fixnum is deprecated
C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:89: warning: constant ::Fixnum is deprecated
# $? => 0
    uses builtin gems when installing to system gems (FAILED - 1)


Retried examples: 0

Failures:

  1) bundle cache when there is a built-in gem uses builtin gems when installing to system gems
     Failure/Error: raise "OMG `#{path}` does not exist!" unless File.exist?(path)

     RuntimeError:
       OMG `C:/Projects/bundler/tmp/gems/remote1/gems/C:/Projects/bundler/tmp/.tmp/builtin_gem-1.0.2/builtin_gem-1.0.2.gem.gem` does not exist!

       Commands:
       $ C:/Ruby24-x64/bin/ruby.exe -rrubygems -S gem --backtrace generate_index
       Generating Marshal quick index gemspecs for 64 gems
       ................................................................
       Complete
       Generated Marshal quick index gemspecs: 0.163s
       Generating specs index
       Generated specs index: 0.002s
       Generating latest specs index
       Generated latest specs index: 0.002s
       Generating prerelease specs index
       Generated prerelease specs index: 0.001s
       Compressing indices
       Compressed indices: 0.009s
       C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:22: warning: constant ::Fixnum is deprecated
       C:/Projects/bundler/tmp/gems/base/gems/builder-2.1.2/lib/builder/xchar.rb:89: warning: constant ::Fixnum is deprecated
       # $? => 0
     # ./spec/support/helpers.rb:330:in `block in install_gems'
     # ./spec/support/helpers.rb:314:in `each'
     # ./spec/support/helpers.rb:314:in `install_gems'
     # ./spec/support/helpers.rb:411:in `system_gems'
     # ./spec/support/builders.rb:743:in `_build'
     # ./spec/support/builders.rb:456:in `block in build_with'
     # ./spec/support/builders.rb:452:in `each'
     # ./spec/support/builders.rb:452:in `build_with'
     # ./spec/support/builders.rb:420:in `build_gem'
     # ./spec/cache/gems_spec.rb:92:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 5.07 seconds (files took 0.94038 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/cache/gems_spec.rb:99 # bundle cache when there is a built-in gem uses builtin gems when installing to system gems

```

---

This path `C:/Projects/bundler/tmp/gems/remote1/gems/C:/Projects/bundler/tmp/.tmp/builtin_gem-1.0.2/builtin_gem-1.0.2.gem.gem` that it is failing on looks very broken. 

Turns out the code "installing" the gems for these tests doesn't handle the `C:` for Windows:
https://github.com/janpio/bundler/blob/7a872bd110a2eac2afb4385d881a3b7991a46272/spec/support/helpers.rb#L322

I will create a PR that fixes that.

### PR DESCRIPTION
**Pull request by janpio**
### What was the end-user problem that led to this PR?

Some tests were failing on Windows with strange paths not existing.

### What was your diagnosis of the problem?

Turns out a regex in the helper for paths didn't fire on Windows paths as they start with something like `C:/`.

### What is your fix for the problem, implemented in this PR?

So I adapted the regex to also match Windows paths.

### Why did you choose this fix out of the possible options?

... which seemed like the right thing to do here.

---

Fixes 21 test failures on Windows.

closes #6892

### CODE REVIEW

**Comment by janpio** [comment]
Ugh, regresses on non-Windows :/

File: spec/support/helpers.rb [hunk 1]
```diff
@@ -318,7 +318,7 @@ def install_gems(*gems)
             Dir.chdir(root) { gem_command! :build, gemspec.to_s }
           end
           bundler_path = root + "bundler-#{Bundler::VERSION}.gem"
-        elsif g.to_s =~ %r{\A/.*\.gem\z}
+        elsif g.to_s =~ %r{\A[A-Z]?:/.*\.gem\z}
```
Comment (deivid-rodriguez) [inline spec/support/helpers.rb]: Try

```suggestion
        elsif g.to_s =~ %r{\A(?:[A-Z]:)?/.*\.gem\z}
```

**Comment by deivid-rodriguez** [comment]
I think this one should be ok with the fixed regexp. The initial attempt is forcing paths not starting with an uppercase letter to start with `:`, which does not happen on Linux.

File: spec/support/helpers.rb (hunk 1 above)
Comment (janpio) [reply spec/support/helpers.rb]: Hm, only now I looked at this: What is the first `?:` for? Looking at it now, I think I should just have made the `?` apply to the `[A-Z]` and `:`.

Comment (deivid-rodriguez) [reply spec/support/helpers.rb]: Yeah, `([A-Z]:)?` probably works too. The `?:` only indicates that the group does not need to be captured. See https://ruby-doc.org/core-2.6.1/Regexp.html#class-Regexp-label-Grouping.

Comment (janpio) [reply spec/support/helpers.rb]: TIL 👍

Comment (deivid-rodriguez) [reply spec/support/helpers.rb]: Which version do you prefer? I don't have a strong opinion.

Comment (janpio) [reply spec/support/helpers.rb]: Yours of course, adds useful functionality. I didn't even know this was possible and sometimes avoided `(...)` because of that reason, so 👍

Comment (deivid-rodriguez) [reply spec/support/helpers.rb]: Ok!

**Comment by deivid-rodriguez** [comment]
@bundlerbot r+

**Comment by deivid-rodriguez** [comment]
Thanks for all the recent fixes @janpio!
